### ISSUE TITLE
Line characters alternatives

### ISSUE THREAD

**Issue by SimWhite** [larsenwork/monoid#101]
It would be nice to have an ability to choose alternatives for the ASCII lines glyph.

Now it looks like:
![](https://xdrops.in/ZC3pwJJA1dCb1BlhrexuTuXZ.png)

And it would be nice to see something like:
![](https://xdrops.in/8moIi0erOVHxs9iKkXQh3rFc.png)

**Comment by larsenwork** [comment]
There are currently no line characters in the font so they most be pulled from somewhere else. 

They could be a nice addition though. Please request in #12 with graphemica links to all characters needed so I know which ones to add.

**Comment by larsenwork** [comment]
Closing this as it's a character request and as such belongs in #12  :smile:
