### ISSUE TITLE
Add Monoisome to the zip

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#104]
I thought https://github.com/larsenwork/monoid/blob/master/Scripts/prepare_release.sh#L7 and https://github.com/larsenwork/monoid/blob/master/Scripts/prepare_release.sh#L18 would do the trick

**Comment by larsenwork** [comment]
scratch that - better to keep it by it self to save space.

**Comment by jozsefk9** [comment]
quick Brown fox jumps over the Lazy dog


J. K.
--
N9005
