### ISSUE TITLE
Add Glyphicons to Monoisome

### ISSUE THREAD

**Issue by mikebronner** [larsenwork/monoid#108]
Add the common Glyphicons to Monoisome as used with Twitter Bootstrap:

http://getbootstrap.com/components/#glyphicons

**Comment by larsenwork** [comment]
That'd require special permission since they aren't released under a free license.

**Comment by mikebronner** [comment]
Sent email to Jan Kovarik to see if he will grant us permission.

**Comment by larsenwork** [comment]
:+1: got the cc

**Comment by mikebronner** [comment]
Unfortunately the creator of Glyphicons does not wish to be in the same font as Font-Awesome, and has not given us permission to use it at this time.

**Comment by mikebronner** [comment]
Resurrecting this thread, as Jan gave permission to use it as a separate font.

**Comment by mikebronner** [comment]
@larsenwork Would it be a good idea for me to go ahead and make a mapping file for Glyphicons the same way we did for Font-Awesome? I would be happy to get a jump on this over the weekend.

**Comment by larsenwork** [comment]
Would be great - I probably won't have any time before sunday to look at it.

Do you know your way around batch replacing with e.g. sed or something similar? That's how I created the .fea for Monoisome from the css file in 5 minutes only missing the glyph names - saved a lot of time:)

**Comment by mikebronner** [comment]
I'll play around with it ... I have not (and probably won't) installed FontForge on my system, as it requires X11, and Java, and other crud which makes me want to take a shower. :)

Using Glyph app to inspect fonts, maybe there are some internal functions to export glyph names, etc. From there I can batch process using my favorite editor. :)

**Comment by larsenwork** [comment]
👍 fontforge isn't needed for any of the .fea stuff - just make sure you only include the .fea file and not the actual font here on github as it isn't an open source font

**Comment by mikebronner** [comment]
Will do :)

**Comment by mikebronner** [comment]
Closing for now, unfortunately haven't been or will be able to work on this due to time constraints. :(
