### ISSUE TITLE
Problems with Chinese

### ISSUE THREAD

**Issue by lldong** [larsenwork/monoid#109]
With Monoid-Regular-12 in Xcode, Chinese font is too small:
<img width="142" alt="screen shot 2015-08-02 at 12 35 02 am" src="https://cloud.githubusercontent.com/assets/528204/9022616/ab259080-38ae-11e5-8fa0-a053d4826a93.png">

**Comment by larsenwork** [comment]
Thanks. The font doesn't support Chinese (would be a huuuuuge task) so the chinese font used is another font picked by xcode. 

What you can do is change the metrics of Monoid using FontForge. (http://fontforge.github.io)

  1. Open the font
  2. Press cmd+shift+f
  3. Select "general"
  4. Change ascent to e.g. 1664 (+ notice "Scale Outlines" is unchecked):
![screen shot 2015-08-01 at 20 58 27](https://cloud.githubusercontent.com/assets/3859425/9023153/13a06528-3890-11e5-9ddc-9dff96137157.png)

**Comment by larsenwork** [comment]
Then press "OK" and File -> generate font

**Comment by lldong** [comment]
Thanks @larsenwork.

**Comment by larsenwork** [comment]
Did it work?

**Comment by lldong** [comment]
@larsenwork Yes, it works. This issue can be closed now.
