### ISSUE TITLE
Make releases of source for easier packaging in Linux distribution

### ISSUE THREAD

**Issue by romildo** [larsenwork/monoid#110]
Versioned releases are very desired for easier packaging `monoid` fonts for Linux distributions. Please do them.

See for instance the bug entry [556108](https://bugs.gentoo.org/show_bug.cgi?id=556108) in Gentoo Linux bugzilla.

**Comment by larsenwork** [comment]
How does one do them?

**Comment by romildo** [comment]
Currently there is a proposed [package for Gentoo Linux](https://556108.bugs.gentoo.org/attachment.cgi?id=407850) which just clones the master git repository and compile the fonts from it.

The [Readme.md](https://github.com/larsenwork/monoid/blob/master/Readme.md) from git repository contains a table with version numbers, date, changes, and author. The latest version in this table is `0.60+0.10` from `2015.07.31`. Maybe for each new version a release could be done.

For the Linux distribution point of view I think the most important would be the availability of an archive (.tar.gz or similar) for each version.

**Comment by romildo** [comment]
Notice that what we want is a versioned archive of the *source* of `monoid`. So there is no need to compile the font to produce this archive.

It would be the responsibility of the packager for the Linux distribution to produce a binary package from the source code released by the authors.

**Comment by larsenwork** [comment]
Cheers, sounds like something that could easily be built into the scripts - I know @chase is busy right now so it's something someone else need to look into :)

**Comment by copyninja** [comment]
@larsenwork We need you to just tag the release in git repositories. for eg `git tag 0.60` and push it to github. Github will automatically provide us archive for download at [https://github.com/larsenwork/monoid/releases](releases) page of your repository. It would be great if you can do the tagging!.

**Comment by larsenwork** [comment]
@copyninja Cheers, done: https://github.com/larsenwork/monoid/releases/tag/0.60

**Comment by larsenwork** [comment]
If it looks good then please close this and I'll tag future releases

**Comment by copyninja** [comment]
@larsenwork Yep thanks a lot. I can't close the bug as I'm not the reporter!.
