### ISSUE TITLE
A few kerning issues

### ISSUE THREAD

**Issue by p-e-w** [larsenwork/monoid#111]
![monoid-kerning-issues](https://cloud.githubusercontent.com/assets/2702526/9090851/f9bc5aee-3b9c-11e5-84e2-3812842c9a1a.png)

`Media`: `i-a` spacing is a bit too much

`Powerline`: `r-l` spacing is far too much, it almost looks like two separate words

`Semi-condensed`: The hyphen is closer to the `c` than to the `i`

`editors`: `r-s` spacing is slightly too much, making the `s` appear somehow separate

`supersized`: The `si` looks a bit like a separate entity

`writing`: `w-r` spacing is too little, looking cramped. `n-g` is also a bit close together

**Comment by larsenwork** [comment]
Powerline, i-c and writing can be improved. 

Not sure about the rest - you might want to try it with the stemmed i instead

**Comment by rzlourenco** [comment]
Could this be related to ligatures?
With ligatures:
![screenshot from 2015-08-08 11-19-39](https://cloud.githubusercontent.com/assets/2820998/9150079/d32a6888-3dbf-11e5-810f-30903d6c8fb8.png)
Without ligatures:
![screenshot from 2015-08-08 11-19-58](https://cloud.githubusercontent.com/assets/2820998/9150080/dd156a6e-3dbf-11e5-8bbd-fe999a5517e9.png)
Note that with ligatures the characters are more evenly spaced. Without them, some seem to cluster (i.e. `smi` in `dismiss` and `on` in `function`). The screenshots were taken on Firefox 39 on Linux.

**Comment by larsenwork** [comment]
I've improved "Powerline" and "Semi-condensed" the rest can't really be improved or is a matter of not having ligatures turned on as @rzlourenco said

**Comment by larsenwork** [comment]
Will be included in next update

**Comment by larsenwork** [comment]
improvements added in 0.61
