### ISSUE TITLE
Please release versioned archive for Monoid source

### ISSUE THREAD

**Issue by copyninja** [larsenwork/monoid#114]
Hi,

I intend to package monoid for [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794245), it would be great if you can versioned tarball/zip archive of Monoid source. This would allow us to track the new releases of monoid, using Debian watch interface. Here is an example of [watch interface](https://qa.debian.org/cgi-bin/watch?pkg=pugixml_1.4-1) in action.

**Comment by larsenwork** [comment]
duplicate of #110 no?

As written there it should be easy to write into the build scripts so it gets created automatically but I have no linux experience and chase is currently busy so someone else will have to look into it.

**Comment by larsenwork** [comment]
assumed duplicate so closing, reopen if it isn't the case

**Comment by copyninja** [comment]
@larsenwork Thank you I missed that.

**Comment by amadio** [comment]
Any chance we could get releases of the compiled-in fonts? That would eliminate a dependency on fontforge. Thanks!

**Comment by larsenwork** [comment]
@amadio of the default version or all these: https://github.com/larsenwork/monoid/tree/release ?

**Comment by amadio** [comment]
The default version should do.

**Comment by amadio** [comment]
Never mind. I mirrored the compiled files in Gentoo for now. Thanks for the great font!

**Comment by larsenwork** [comment]
:+1:
