### ISSUE TITLE
Font Awesome fa-empire [&#xf1d1;]

### ISSUE THREAD

**Issue by NSHenry** [larsenwork/monoid#115]
fa-empire [&#xf1d1;] renders as Ḱ in Atom

**Comment by mikebronner** [comment]
@NSHenry Thanks for the heads-up on this. I did make a speaking error when transcribing the character set. 

@larsenwork I submitted a PR with the correction.

**Comment by larsenwork** [comment]
@mikebronner great, merged - I'll update the source later this weekend. Let's leave this open until I've pushed the fix

**Comment by larsenwork** [comment]
![screen shot 2015-08-09 at 09 59 22](https://cloud.githubusercontent.com/assets/3859425/9154025/0d4939ae-3e7e-11e5-9661-62d0eb60882b.png)
