### ISSUE TITLE
font size increase between 0.40 and 0.60

### ISSUE THREAD

**Issue by akorobov** [larsenwork/monoid#117]
It looks like font size in 0.60 was increased significantly. Here's comparison at size 11 of Menlo, Monoid 0.40 and 0.60:
<img width="783" alt="screen shot 2015-08-07 at 2 03 14 pm" src="https://cloud.githubusercontent.com/assets/102709/9145964/9283851a-3d0d-11e5-9cfe-6b8da3f60e15.png">

Was this intentional?

**Comment by larsenwork** [comment]
yep, fontsize is just an arbitrary number and I needed something that was factor 3:4 so it was either 9pt:12px or 12pt:16px

And since the font is ≈13px I changed it to 12px in https://github.com/larsenwork/monoid/commit/4bbcc3ee706d7d6d26fd30e0dc85fd23d7064ccf
