### ISSUE TITLE
!== rendered incorrectly

### ISSUE THREAD

**Issue by targeter** [larsenwork/monoid#118]
I'm using Atom on OSX (retina), and `!==` is rendered like this, which seems wrong:

<img width="38" alt="screen shot 2015-08-08 at 22 42 27" src="https://cloud.githubusercontent.com/assets/54348/9152193/c5909e86-3e1e-11e5-9908-a3d4c1e818e1.png">

**Comment by larsenwork** [comment]
https://github.com/larsenwork/monoid/issues/25#issuecomment-126350486
