### ISSUE TITLE
Win10 (32-bit): Unable to install font

### ISSUE THREAD

**Issue by unquieted** [larsenwork/monoid#119]
Steps to replicate: 

In Windows 10 (32 bit): 

1. Download Monoisome-Regular.ttf
2. Navigate to file, right-click and chose "Install"

RESULT: 

"Installing Fonts" Dialog Box appears, with message: 

"Cannot Install Monoisome-Regular.ttf

The file C:\Users\ABC\...\Monoisome-Regular.ttf does not appear to be a valid font."

**Comment by larsenwork** [comment]
Thanks for the report - not sure what's the culprit. Needs someone with win10 to verify/de-verify this.

**Comment by rizvn** [comment]
this seems to be a windows 10, issue. Cant seem to open or install any ttf or otf fonts

**Comment by larsenwork** [comment]
@rizvn cheers, not something I can fix then :smile:

**Comment by rizvn** [comment]
The fix bizzarely is to enable Windows firewall, to install fonts on
Windows10

@rizvn <https://github.com/rizvn> cheers, not something I can fix then [image:
:smile:]

—
Reply to this email directly or view it on GitHub
<https://github.com/larsenwork/monoid/issues/119#issuecomment-135020332>.
