### ISSUE TITLE
Regular and Bold should not have different widths

### ISSUE THREAD

**Issue by BenjaminNitschke** [larsenwork/monoid#120]
Normally all text is regular and things work fine, everything is mono-spaced.

But using Visual Studio and plugins or certain font settings makes some text bold (xml comments, TODO, strings, whatever). However the bold version of Monoid has bigger width and moves everything way to the right. This is especially annoying as while typing things are regular and then it pops back and forth as VS or the plugin detects the keywords.

There should be an option to make all monoid fonts styles (regular, bold, italic) same width.

**Comment by larsenwork** [comment]
Sounds like you're mixing monoid tight/normal/loose 

Regular, retina, italic and bold are all same width

**Comment by larsenwork** [comment]
@BenjaminNitschke is this a visual studio only problem or do you have it in other programs too?

**Comment by BenjaminNitschke** [comment]
Thanks for the answer, I might have used it wrong, maybe the website should mention to install all font types. Just installing the regular font makes the problem I described happens in any program (see attached images, the second one with bold selected has more font width): Visual Studio, Notepad, Word, Notepad++, etc.
![notepadmonoidregular](https://cloud.githubusercontent.com/assets/1650127/9171727/3972dd64-3f6e-11e5-87b1-042500718289.png)
![notepadmonoidregularbold](https://cloud.githubusercontent.com/assets/1650127/9171730/40d8c2d0-3f6e-11e5-9cf5-d0dff540a5d0.png)

Now that I have installed the bold, italic and retina font styles as well, the problem goes away :)

**Comment by larsenwork** [comment]
How should the instructions be clearer? Why would you assume bold + italic would work without installing them?

**Comment by BenjaminNitschke** [comment]
Well I don't install fonts every day and normally it is just a single .ttf file and it is all in there, that would certainly make things easier.

**Comment by larsenwork** [comment]
.ttf can't have multiple weights
