### ISSUE TITLE
incorrect rendering of ligatures/code points disappearing

### ISSUE THREAD

**Issue by smason** [larsenwork/monoid#122]
Hi,
I've just been playing with Monoid and found that the character sequence `<==>` (i.e. four UTF code points—`<`,`=`,`=`,`>`) only gets rendered as the precomposed ligature:

 ![double equals greater](https://cloud.githubusercontent.com/assets/1433005/9169766/57715714-3f55-11e5-99fe-6a4ab039e7d9.png)

This is under OSX 10.10 and occurs within LightTable and the system program FontBook. I would have expected it to display the non-precomposed code points, or at least not loose the first '<' completely.  I've not looked for further examples.
This is a bit scary, but otherwise a great typeface!
Cheers,
  Sam

**Comment by rzlourenco** [comment]
This issue also seems to be present on Atom in Linux.

**Comment by larsenwork** [comment]
I've thought about this and one way to make the ligatures "safer" would be to "wrap" them in spaces so e.g. only ` `,`<`,`=`,`=`,`>`,` ` get's recognised 

But I don't know enough coding languages to know which ligatures could be "wrapped" in spaces. 

![screen shot 2015-08-10 at 14 00 13](https://cloud.githubusercontent.com/assets/3859425/9170995/28a00c4c-3f68-11e5-92c1-98bc841962e9.png)
![screen shot 2015-08-10 at 14 00 16](https://cloud.githubusercontent.com/assets/3859425/9170996/28a1e54e-3f68-11e5-824a-62bb6f992cce.png)

**Comment by larsenwork** [comment]
https://dl.dropboxusercontent.com/u/3019777/Monoid-Regular.ttf should fix it, please test

**Comment by smason** [comment]
Thanks for looking into this!
I thought that there was some sort of finite state machine described by the font file.  I thought that the table definitions could be reordered to "fix" this bug, but this is only my inference from looking at other similar projects.
I've also tried using "Fira Code" and this exhibits what I would consider to be correct behaviour without having the operator surrounded by spaces.

**Comment by smason** [comment]
I've just tried using the updated font and it works as expected…

**Comment by larsenwork** [comment]
@smason Monoid has a unique approach to ligatures (compared to e.g. Fira Mono and the fonts I've seen so far) in that I don't use ligatures but contextual alternates because I want the font to still be monospaced which e.g. Fira mono isn't. 

Details here under "technical issues" : https://medium.com/@larsenwork/ligatures-coding-fonts-5375ab47ef8e

**Comment by larsenwork** [comment]
*Fira Code

**Comment by larsenwork** [comment]
fixed in 0.61
