### ISSUE TITLE
Font does not look smooth in Visual Studio 2013 IDE

### ISSUE THREAD

**Issue by MrClyfar** [larsenwork/monoid#123]
Hi.

This might be an issue with my Windows 8.1, but I'm not sure since other fonts look fine.

I'm using Monoid with Visual Studio 2013, and I've noticed that the font does not look too good until 
I increase the font to 18pt. I'm using a 24inch Samsung Syncmaster monitor. I've attached a screenshot of the font as I see it at 14pt.

![monoid 14pt in visual studio](https://cloud.githubusercontent.com/assets/700064/9181886/55c0773e-3f9f-11e5-8724-12aa0a4dccf8.jpg)

Some of the letters look a little uneven in weight - a bit heavier in certain parts of the letter than others.

To compare, here is the font at 18pt:

![monoid 18pt in visual studio](https://cloud.githubusercontent.com/assets/700064/9181985/e6350c6c-3f9f-11e5-8d2d-747604b13f85.jpg)

At 18pt the font definitely looks better. But 18pt is a bit too big for me to work with as a coder.

I have tried adjusting ClearType but that made no difference. Is there another setting, either Windows or Visual Studio, I could look at changing in order to improve the quality?

**Comment by larsenwork** [comment]
It's designed for 9pt (and thus also 18pt as you've noticed) 

To achieve that sharpness at 9pt the font is thinner than most other regular weights. I don't know why windows font rendering system thinks uneven thickness is an acceptable "solution". 

This is how it looks at 18px (≈14pt) on my system: 
![screen shot 2015-08-10 at 21 51 49](https://cloud.githubusercontent.com/assets/3859425/9182361/812113d8-3faa-11e5-8a1d-9cec90f973ee.png)

**Comment by MrClyfar** [comment]
Hiya.

Thanks for response.

Does that mean I just have to stick with 18pt on my system in order to use the font without the uneven thickness, as in, it's a Windows thing? :)

I have noticed this oddity with other fonts too.

Cheers.

**Comment by larsenwork** [comment]
Common Windows thing. Maybe more prominent in Monoid compared to other fonts since it's thinner than most regular weights.
