### ISSUE TITLE
Wrong character appears for bit shift.

### ISSUE THREAD

**Issue by gvela024** [larsenwork/monoid#127]
Using Eclipse Luna.

I type in: 
```
uint8_t blah;

// do some stuff

blah <<= 1;
```

Monoid turns this into a less than sign followed by a less than or equal to sign. Haven't tried any other variations but I'm assuming there is a similar issue with `>>=`.

**Comment by larsenwork** [comment]
cheers, fixed <<= 
>>= is currently a ligature as used in haskell...not sure what to do about it...

![screen shot 2015-08-26 at 15 22 00](https://cloud.githubusercontent.com/assets/3859425/9494459/3c2b5f50-4c06-11e5-8407-cad8c1cd18f3.png)

**Comment by larsenwork** [comment]
I'll upload a new version soon (probably this weekend).
