### ISSUE TITLE
<- ligature does not show the < (at least in eclipse)

### ISSUE THREAD

**Issue by xelax** [larsenwork/monoid#128]
When I type 
<- <<-  ->> ->

I see: 

![mon](https://cloud.githubusercontent.com/assets/438260/9477273/4b733f7c-4b26-11e5-809f-4c02aad3625c.png)

this is on os x 10.10.5 with monoid retina, but it appears to work fine with monoisome regular

**Comment by larsenwork** [comment]
Cheers, was an error - is now fixed. I'll upload a fix soon (weekend probably)
![screen shot 2015-08-26 at 15 23 31](https://cloud.githubusercontent.com/assets/3859425/9494497/724e4a34-4c06-11e5-9904-f4930e4ed1f3.png)
