### ISSUE TITLE
Upcoming improvements/adjustments

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#129]
I've started new work here in august + studying iOS development, php language + some freelance stuff + helped my cousin renovate her apartment so I've been busy...but I'll push an update this weekend with various bug fixes, some new ligatures, modified letters, center aligned retina font and stuff...

Have I missed anything critical? Or any other suggestions/ideas?

Wider equal sign when surrounded by spaces
![screen shot 2015-08-26 at 15 50 59](https://cloud.githubusercontent.com/assets/3859425/9495135/4afb3cea-4c0a-11e5-9c6f-6af03968b0f5.png)

New letter 4
![screen shot 2015-08-26 at 15 51 05](https://cloud.githubusercontent.com/assets/3859425/9495136/4b15b9c6-4c0a-11e5-9c8e-9c7e2b98baa9.png)

**Comment by xelax** [comment]
I found a problem with double "m":
this how summary is rendered using monoisome 11:

<img width="52" alt="summary" src="https://cloud.githubusercontent.com/assets/438260/9553164/15bf9a62-4d72-11e5-830e-1a830605c34e.png">

**Comment by rzlourenco** [comment]
I like "old" 4, I think it makes Monoid more differentiated.
