### ISSUE TITLE
Distributing Monoid with disabled ligatures

### ISSUE THREAD

**Issue by Calinou** [larsenwork/monoid#131]
Since ligatures look bad in lots of software (or you just don't want them), why not distribute a NoLigatures version of Monoid?

**Comment by larsenwork** [comment]
Just select no ligatures on the website?

**Comment by Calinou** [comment]
> Just select no ligatures on the website?

I did not realize that changing options changed both preview and download. Maybe it should be made more clear.

Thanks a lot!
