### ISSUE TITLE
Ligature request: =/= and =:=

### ISSUE THREAD

**Issue by tuncer** [larsenwork/monoid#134]
`=/=` and `=:=` are part of Erlang syntax.

`=/=` and `/=` have different semantics in Erlang (as do `==` and `=:=`), so displaying the same ligature for both would be wrong.

**Comment by larsenwork** [comment]
there should be a ligature for =:= already 


ligature
![screen shot 2015-12-10 at 21 37 45](https://cloud.githubusercontent.com/assets/3859425/11727783/472d0c04-9f86-11e5-8656-b521ae832763.png)


without
![screen shot 2015-12-10 at 21 38 17](https://cloud.githubusercontent.com/assets/3859425/11727791/57947460-9f86-11e5-98d3-bdead0f7d7e1.png)


Do you have a specific idea as to how a ligature could improve =/= ?

**Comment by tuncer** [comment]
The mathematical not-equals symbol would make sense for =/=.

**Comment by luben** [comment]
@tuncer we should consider also ligatures for !== that may also be rendered as 3-width non-equality symbol, see the recent discussion in #25

**Comment by tuncer** [comment]
Okay, closing this one, then.
