### ISSUE TITLE
typing '=' results in empty space

### ISSUE THREAD

**Issue by sharmi** [larsenwork/monoid#138]
I downloaded the version available on the website and everytime I type equal to (=) in monoid, I only get empty space.  =  works in other typefaces.

**Comment by Awea** [comment]
Same here on ubuntu 14.04

**Comment by plgruener** [comment]
Are you using the ligature-version? If so, please check if your application supports these features (see section ligature support in README).

**Comment by sirfz** [comment]
Yep, same issue using ligature-version on Gnome-terminal. Use the non-ligature version instead.
