### ISSUE TITLE
How do you use Monoisome?

### ISSUE THREAD

**Issue by smlombardi** [larsenwork/monoid#139]
I installed it and Monoid.

In an Atom html file, I use `<i class="fa fa-plus"></i>` and nothing happens.  FA is linked via a CDN link.

I am on Mac 10.1.1b2  All the other alternate characters work great.

**Comment by larsenwork** [comment]
You have to make sure you're using Monoisome and not monoid - monoid doesn't have those ligatures

**Comment by boazblake** [comment]
I too have this issue... I added Monoisome and nothing changed
