### ISSUE TITLE
Build from Source is crashing with segmentation fault

### ISSUE THREAD

**Issue by copyninja** [larsenwork/monoid#140]
Hi,

I'm trying to build Monoid from the source for Debian packaging and I observe a segfault when I execute following command

```sh
Scripts/build.py 1 0 Monoid.sfdir
```
Above is just example it crashes for every font with following message

```
Failed to find NameList: AGL For New Fonts
Segmentation fault (core dumped)
```

I'm using python-fontforge and fontforge version `20120731.b-5` Does monoids needs newer version for fontforge?

**Comment by luben** [comment]
I have installed FontForge from source and it works. It crashes with the debian package.

**Comment by larsenwork** [comment]
@luben thanks for helping - assuming fixed

**Comment by copyninja** [comment]
Sorry for delayed responsoe. So it looks like new fontforge is badly needed in Debian. Thanks for conifrming
