### ISSUE TITLE
Weird "mm" ligature in Monoisome

### ISSUE THREAD

**Issue by atomicbird** [larsenwork/monoid#142]
Typing a word that includes "mm" produces a weird ligature. For example, the word "programming" ends up looking like this:

<img width="308" alt="monoisome-1" src="https://cloud.githubusercontent.com/assets/15008/10858522/4c83b2ce-7f1b-11e5-8582-509f9bae28b3.png">

This is annoying enough when it appears in comments, but it's absolutely maddening when attempting to use a time format that includes something like "HH:mm:ss". This makes the time format appear to be simply wrong even if it's correct and works.

This is using Monoisome, in Xcode, on OS X.

**Comment by atomicbird** [comment]
I get the same thing in TextEdit, too.

**Comment by Iftahh** [comment]
Same in Eclipse, OS X also

**Comment by msiebert** [comment]
I get the same issue in Atom on Linux. Also Monoisome.

**Comment by larsenwork** [comment]
cheers, will look into it this christmas :+1:

**Comment by larsenwork** [comment]
fixed in next push (probably this weekend)

**Comment by evxn** [comment]
@larsenwork
Hi, really weird, this issue was closed 3 years ago, but I still can reproduce it on Webstorm.  Installed Monoisome on Ubuntu today from your official site.

**Comment by evxn** [comment]
related to #191

**Comment by Vampire** [comment]
That's not weird but sad.
The latest release is from 2015-08-11, this issue was fixed in december 2015, so or course you can reproduce it. :-(

@larsenwork is this project dead or do you still support it and also fix bugs and maybe do a release?
I also have several bugs to report, including this one.

**Comment by darrelfrancis** [comment]
This is fixed now in the font downloaded today, 23 Dec 2018. 
However, do we really need an mm ligature? The separate "mm" is easy enough to understand whereas the conjoined mm needs a second look to properly understand.
![image](https://user-images.githubusercontent.com/20881844/50381444-1b4aa200-067f-11e9-8967-d2d942c30cfa.png)

**Comment by Iftahh** [comment]
I certainly don't want the mm ligature

**Comment by shaman007** [comment]
@larsenwork the updates are not present in the files available for the download.
