### ISSUE TITLE
Size 9 shown as size 11?

### ISSUE THREAD

**Issue by estan** [larsenwork/monoid#143]
This is might not be a bug in Monoid, but I'd like to get to the bottom of it.

Normally I use Source Code Pro at size 9 in Konsole, and it looks like this:

![konsole_source_code_pro_at_size_9](https://cloud.githubusercontent.com/assets/86675/10862686/14447c98-7fb3-11e5-8635-0889a69095cc.png)

Recently I tried out Monoid at size 9, and it looks like this:

![konsole_monoid_at_size_9](https://cloud.githubusercontent.com/assets/86675/10862691/23c16546-7fb3-11e5-8bf7-3bb8e343c141.png)

Why is Source Code Pro shown properly as 9 pixels high, but Monoid as 11 pixels high? Shouldn't they be the same height? I actually like the look of Monoid better, but I need it smaller (but still crisp).

**Comment by estan** [comment]
Forgot to say: All my other monospace fonts (Nimbus Mono, Ubuntu Mono, Liberation Mono, ...) show up at 9 px height when the size is set to 9.

**Comment by luben** [comment]
In your screenshots the same number of lines take the same space of the screen. Monoid letters look bigger because the bodies of the letters are bigger and the line spacing is smaller. You can compare with PragmataPro that uses similar approach to improve readabity

**Comment by estan** [comment]
Aha. I see. Thanks, closing this issue.
