### ISSUE TITLE
Partial IntelliJ support

### ISSUE THREAD

**Issue by igorsantos07** [larsenwork/monoid#150]
It seems IntelliJ and friends have partial support for Monoid ligatures. Through [FiraCode instructions](https://github.com/tonsky/FiraCode/wiki/Intellij-products-instructions) I could enable ligatures on it's renderer, getting Hasklig and Firacode to work (although the last one has performance issues).

However, Monoid is displaying a very weird behaviour, as the same ligature is only being displayed sometimes (`->`):
![screenshot_535](https://cloud.githubusercontent.com/assets/532299/12075032/99e3d2c2-b159-11e5-8062-64d8ef916666.jpg)

I tried to reproduce the behaviour but was not able to understand what triggers it. It seems other ligatures are not displayed at all, like `:: =>`. Opening another file I saw the `!=` (and maybe others) for a brief moment, but then highlighting happened and they vanished - while fa icons and `<!--` are still displayed.

The behaviour is observed both on Monoid Loose and Monoisome.

**Comment by igorsantos07** [comment]
I would add here that Monoisome icons behave very weird, maybe PHPStorm cannot understand when many chars are turned into one. The original text is "hidden" but the individual letters can be seen with the cursor. I could see this is not a system behaviour as the icons work fine on gEdit/Pluma.

![screenshot_537](https://cloud.githubusercontent.com/assets/532299/12075104/d24969ae-b15b-11e5-8582-60cebfb11d15.jpg)

**Comment by larsenwork** [comment]
@igorsantos07 it's because I'm doing ligatures using contextual alternates (because this makes it work in other editors/terminals that e.g. fira code doesn't support). 
But for the icons i monoisome I'm using normal ligatures so that's why they are behaving differently. I don't think I'll be changing this unless theres another way that all editors support
