### ISSUE TITLE
code ligatures  !== and === are not working in iOS

### ISSUE THREAD

**Issue by mamartins** [larsenwork/monoid#151]
hello,

When I write !== or === on atom or vscode this is what you get:
<img width="222" alt="screen shot 2016-02-18 at 22 13 45" src="https://cloud.githubusercontent.com/assets/856772/13160008/eaf37f20-d68c-11e5-86b1-a28cf8aa6786.png">

**Comment by gypsydave5** [comment]
Yes - I'm seeing the same in Terminal

**Comment by mamartins** [comment]
no fix for this?

**Comment by rzlourenco** [comment]
I think the first one is mean to be that way. I'm not sure about the second one, though.

**Comment by luben** [comment]
the second one was ment to be that way I think. The first one is 3 lines crossed on my screen.

**Comment by larsenwork** [comment]
![screen shot 1](https://cloud.githubusercontent.com/assets/3859425/16169698/b05267e6-3537-11e6-9ff1-0adbb89c329a.png)
I've experimented with this, not sure if I like it though :/

**Comment by larsenwork** [comment]
See them all here: 
https://github.com/larsenwork/monoid/issues/25#issuecomment-163748734

**Comment by larsenwork** [comment]
I've decided to add them all, will be in next update

**Comment by joshburgess** [comment]
I left a screenshot in the referenced issue above of these working in Windows in VS Code. These are working for me there, but not on MacOS/OSX. Something is wrong.
