### ISSUE TITLE
💡 invisible characters 

### ISSUE THREAD

**Issue by salarmehr** [larsenwork/monoid#152]
Providing a symbol for each invisible characters is really useful while coding.  (including:     BOM, Combining Grapheme Joiner, Left-to-right mark / Right-to-left mark, Soft hyphen Word joiner, Zero-width joiner, Zero-width non-joiner, Zero-width space) (https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Special-purpose_characters) 

https://www.microsoft.com/typography/otfntdev/glyphs.htm
https://commons.wikimedia.org/wiki/Category:IEC_60417_symbols

**Comment by larsenwork** [comment]
@salarmehr this is easy, please just write the unicode values of the characters and I'll add them 😄

**Comment by salarmehr** [comment]
Thanks.
![bgh2t 1](https://cloud.githubusercontent.com/assets/2582036/14582496/c2a54e4c-041b-11e6-9a6e-79f48c367ca1.png)

**Comment by larsenwork** [comment]
added to all weights in next update
