### ISSUE TITLE
Fix ligature support for Kleisli arrows

### ISSUE THREAD

**Issue by verandaguy** [larsenwork/monoid#156]
Currently, when working with Haskell (not that that's particularly relevant), inputting the Kleisli arrow operators: `<=<` and `>=>` results in the ligatures producing `≤<` and `≥>`, respectively.

This leads to readability issues when working with Haskell code in an environment where the font is Monoid.

I propose that either ligatures be implemented for the `>=>` and `<=<` trigraphs, or that these arrows explicitly remove the ligatures for `>=`/`≥` and `<=`/`≤` (if this is possible; I have extremely limited experience working with font construction).

This issue is related to #135.

**Comment by larsenwork** [comment]
@verandaguy 
![screen shot](https://cloud.githubusercontent.com/assets/3859425/16169646/57018d76-3536-11e6-9391-fc01c0a47e70.png) took the simple approach, will upload later today after fixing other issues too

**Comment by be5invis** [comment]
@larsenwork Perhaps you can try
```AFDKO
sub greater equal greater by kleislirightarrow;
sub greater equal by gteq;
```
Note the order, longer first.

**Comment by larsenwork** [comment]
@be5invis I use contextual substitution for ligatures so that syntax wouldn't work. (I do it to make the "ligatures" work in misc terminal applications

**Comment by be5invis** [comment]
@larsenwork So this? This is the “original” syntax for chaining substitution, and it can replace all characters matched in one rule.

```AFDKO
sub greater' lookup geaterToKleislirightarrow equal' lookup toSpace greater' lookup toSpace;
sub greater' lookup geaterToGteq equal' lookup toSpace;
```

**Comment by AppShipIt** [comment]
I defer to your aesthetic sense but I'd personally prefer a connected arrow (long `=`).

**Comment by verandaguy** [comment]
@larsenwork the simple approach is good enough -- it's already a huge improvement when it comes to readability. Thanks a lot!

**Comment by larsenwork** [comment]
@be5invis huh, looks like I could simplify my substitutions quite a bit.
