### ISSUE TITLE
Question: Direct download links

### ISSUE THREAD

**Issue by siddharthist** [larsenwork/monoid#160]
I'd like to package Monoid for NixOS, but I can't seem to find direct download links for all the variants. Can you help me out?

**Comment by larsenwork** [comment]
We use circleCI to build it and store the files on rawgit, http://rawgit.com
I don't think there's an easy option to download all (it's ~3000 files if I remember correctly)

**Comment by siddharthist** [comment]
@larsenwork Where can I find the files on rawgit? http://rawgit.com/larsenwork/monoid doesn't show a directory listing.

**Comment by larsenwork** [comment]
@siddharthist I don't think there is any browse-able directory and the easiest thing to do is prolly to fork, modify build scripts to download instead of publish to rawgit and hook it up to another ci

**Comment by siddharthist** [comment]
@larsenwork I won't be forking this repo and setting up a custom CI build in order to package it, that's far too much work for a single font. Thanks anyway! It's an awesome font!

**Comment by JakeChampion** [comment]
You could create a webside using the `gh-pages` branch on this repo to host them :-)

**Comment by larsenwork** [comment]
@siddharthist understood :) 
@JakeChampion already have gh-pages but not allowed to host binaries as per github guidelines as far as I remember
