### ISSUE TITLE
mutt ligatures broken

### ISSUE THREAD

**Issue by honza** [larsenwork/monoid#176]
It's missing the opening `<` in the email addresses, and the `.com` part of the domain is messed up. Is there something that can be done?

![screenshot from 2017-02-13 20-49-53](https://cloud.githubusercontent.com/assets/206357/22911545/aa7fccf2-f236-11e6-9a87-22ec5361ee49.png)

**Comment by larsenwork** [comment]
Mutt as in the email editor? 

If so:
* does the problem appear in other programs (terminal, atom etc) or does it work there? 
* does other ligatures work in the mutt editor?

**Comment by honza** [comment]
Fixed by clearing font caches, rebooting, and installing a non-ligature version of the font. Thanks for an amazing font!
