### ISSUE TITLE
Update README - Sublime Text now supporting ligatures 

### ISSUE THREAD

**Issue by pykong** [larsenwork/monoid#190]
With today's release of Sublime dev 3146+, ligatures are now supported.
https://www.sublimetext.com/3dev

The README should be updated to reflect this change.

**Comment by psomhorst** [comment]
It's only the dev version, though. Maybe wait for release?

**Comment by pyking2** [comment]
The last time I checked **Fira Code** and **Hasklig** already updated their README respectively.
I believe the README should be updated now, stating the version number though.
Just my opinion, I am no the maintainer of this repo.

**Comment by DannyBen** [comment]
Why is this still open? This works beautifully in Sublime Text 3.

**Comment by larsenwork** [comment]
Yeah, I started looking at PRs today, haven't cleaned up issues yet. Will do. 😅
