### ISSUE TITLE
Go OFL

### ISSUE THREAD

**Issue by davelab6** [larsenwork/monoid#20]
Please consider switching from MIT to OFL :)

**Comment by andreaslarsen** [comment]
Problem with OFL is many users don't understand it and contact me asking if x or y is ok - why not MIT?

**Comment by chase** [comment]
@davelab6 There is literally nothing you can do with OFL that you can't do with MIT. MIT is far more permissive and doesn't bar the usage of a font's name in derivatives.

Is it some kind of requirement in a policy somewhere? If that's the case, I suppose Monoid could be dual licensed.

**Comment by andreaslarsen** [comment]
@chase problem is there are two kinds of OFL - those with and those without reserved font name. 

It's a mess really but problem is most font designers use it. I work together with @devalab6 on FontForge and I tried suggesting we removed RFN from our default OFL. it got some odd replies (not form dave or other core members) but others...

**Comment by larsenwork** [comment]
I think we'll keep MIT for now - see no reason to change :)

**Comment by davelab6** [comment]
I can't host it on google fonts then :/

**Comment by larsenwork** [comment]
Why not?

**Comment by larsenwork** [comment]
I'm new to all this but isn't MIT more permissive than OFL? 
Any whoop: How about apache then? (I think I remember seeing some google fonts having that license)

**Comment by larsenwork** [comment]
I've just really grown to not like OFL because I get "spammed" by people not understanding it and asking if it's ok to do this and that (answer is always yes) :sunglasses:

**Comment by davelab6** [comment]
GF is moving all those Apache fonts to OFL ;)

**Comment by larsenwork** [comment]
Oh no...hmm...guess we could always dual license so it's MIT here on GitHub and OFL on Google.

**Comment by davelab6** [comment]
You can add both license files to the repo, that will work

**Comment by larsenwork** [comment]
ok, will do :)
