### ISSUE TITLE
The font is not strictly fixed-width.

### ISSUE THREAD

**Issue by pthfdr-42** [larsenwork/monoid#202]
![2018-03-10-013345_1152x864_scrot](https://user-images.githubusercontent.com/31236558/37220932-1f3e3b6a-2403-11e8-926a-184642eaf9f4.png)
![2018-03-10-014034_1152x864_scrot](https://user-images.githubusercontent.com/31236558/37221219-22ce2ffa-2404-11e8-9c79-554511b57054.png)
This is an example.As you can see, the text is not aligned.
Consider adding a monospace option in your downloads.

**Comment by pthfdr-42** [comment]
It seems that it is being unanswered.
I give up.

**Comment by monolifed** [comment]
You are right. Only "Normal" tracking one seems to be monospaced.
( Retina seems to be non monospaced regardless of tracking)
