### ISSUE TITLE
Visual Studio Code Support?

### ISSUE THREAD

**Issue by joshburgess** [larsenwork/monoid#206]
Is Visual Studio Code support possible? "Visual Studio" is listed in the compatibility chart under partially working, but not VS Code.

**Comment by balupton** [comment]
I already use it fine with VS Code… what problem are you having?

**Comment by joshburgess** [comment]
Nevermind, I'm good. I uninstalled and installed a newer version of the font, and now it's rendering the same in both Atom and VS Code.

Sadly, I have an older version on a Windows machine that is working that has ligatures for `===` and `!==` (JavaScript), and this new version doesn't, but that should be a separate issue. So, I'm going to close this.
