### ISSUE TITLE
Go bold and oblique

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#22]
![monoid](https://cloud.githubusercontent.com/assets/3859425/7966863/0eb05bd2-0a27-11e5-93e5-3f03ef19cac8.png)

As people who look in the source may have noticed I've been fiddling with Monoid Bold and just wanted to share a screenshot. 

I'm trying to keep it over the same grid so typographically I'm making all sorts of mistakes but I wanted to see if it was possible to make it just as crisp as the normal weight.

**Comment by stuartjmoore** [comment]
How about Italic or oblique? I use them for comments, documentation, and literals in my code.

**Comment by larsenwork** [comment]
@stuartjmoore the editors I've used just use fake obliques which at 14px looks just as fine as proper obliques but that might not be the case for all editors?

**Comment by stuartjmoore** [comment]
As far as I can tell, it’s not an option for Xcode.

**Comment by larsenwork** [comment]
Cheers, next update to the master branch will have a test folder with work-in-progress versions of both oblique and bold. So if you can test those and report back at some point it'd be :+1:

**Comment by larsenwork** [comment]
I've opted too only slant it by 11 degrees as it aligns well with the grid. Do you think it's enough?
![monoid](https://cloud.githubusercontent.com/assets/3859425/8166293/26a8f2a2-1397-11e5-8f7a-6b4bebecffb7.png)

**Comment by stuartjmoore** [comment]
Looks pretty good; I'll have to take a closer look later.

PS, it’s not technically [italic](https://en.wikipedia.org/wiki/Italic_type), but oblique roman (preferred in this case I think).

**Comment by larsenwork** [comment]
@stuartjmoore hehe...I know (https://github.com/larsenwork/monoid/issues/22#event-331292653). Oblique was just too long to fit in the screenshot...

**Comment by larsenwork** [comment]
@chase no pressure (you were busy this month;) but the oblique version will probably be ready fairly soon so will be great once the build script supports it.

**Comment by chase** [comment]
Should be able to just add the .sfdir to the build script's font array:
https://github.com/larsenwork/monoid/blob/master/build.py#L14

**Comment by larsenwork** [comment]
@chase but that's too easy :godmode:

**Comment by larsenwork** [comment]
@chase just prior to #34 I did one build that had both regular and obliques resulting in obliques being the default font on the website. 

And semi related: It would be cool if e.g. 
```
Monoid-regular-l.ttf, Monoid-oblique-l.ttf, Monoid Bold-l.ttf (last one not added yet)```
were put in 
```
Monoid-l.zip
```

**Comment by larsenwork** [comment]
@stuartjmoore try these: https://github.com/larsenwork/monoid/tree/master/Testing

**Comment by stuartjmoore** [comment]
Awesome; looking great. Can’t wait for the bold version.

**Comment by chase** [comment]
@larsenwork I'll get on that as soon as I can.

**Comment by larsenwork** [comment]
@chase no stress :)

**Comment by larsenwork** [comment]
@chase it seems like the script generates both oblique + regular both whichever is last https://github.com/larsenwork/monoid/blob/master/build.py#L14 overwrites the other (so with current config only regular gets moved into the release folder).

**Comment by larsenwork** [comment]
@chase just a heads up that I had force fetch to get the build working: https://github.com/larsenwork/monoid/blob/master/circle.yml#L10 
As written in #38 it's probably a good idea to superbuild to a `release2.0` branch until it works without hiccups :smile:

**Comment by chase** [comment]
So sorry about that. What I **should** have done is modify my own fork instead of fiddling with something that works right before your presentation.

**Comment by larsenwork** [comment]
No worries, force fetch fixed it real quick

**Comment by chase** [comment]
Numbers and most swap-able don't have bold versions it seems.

**Comment by larsenwork** [comment]
Nope - work in progress :)

**Comment by larsenwork** [comment]
Bold and oblique complete
