### ISSUE TITLE
Vim doesn't recognize Monoid as a monospace font on Windows

### ISSUE THREAD

**Issue by duckwork** [larsenwork/monoid#23]
When typing `:set guifont=Monoid:h9:cANSI` on gVim in Windows, I get an "Invalid font" error. Monoid also fails to show up on the system font dialog when I input `:set guifont=*`.

I'm guessing that Vim isn't seeing Monoid as a monospace font for some reason.

The original comment was posted on [reddit](https://www.reddit.com/r/web_design/comments/38c6wn/open_source_coding_font_i_made_any_suggestions/cruo8rz?context=3).

**Comment by larsenwork** [comment]
:+1:

**Comment by larsenwork** [comment]
try this: https://dl.dropboxusercontent.com/u/3019777/Monoid-Normal.otf

**Comment by duckwork** [comment]
![screenshot 2015-06-03 16 46 10](https://cloud.githubusercontent.com/assets/584784/7973909/21d4f6e4-0a10-11e5-883b-8aa2a9a05e8c.png)

That did the trick!

**Comment by larsenwork** [comment]
Great - I will update the source now - thanks for the help

**Comment by MarkStega** [comment]
Under Windows 8.1 the OTF file was still needed to get the 'normal' Monoid font select-able in Crimson Editor.
