### ISSUE TITLE
Generate webfonts automatically

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#26]
I saw a pr by @bollwyvl here: https://github.com/tonsky/FiraCode/pull/24 could be cool to have this feature added to monoid too :wink:

**Comment by chase** [comment]
Definitely wouldn't take much effort to get this implemented, but I have a question:
Should it be packaged with the .ttf in the same zip?

I personally think that's the right way to do it, so we don't make the `release` branch explode.

**Comment by larsenwork** [comment]
I was actually thinking about just doing it for the default font and push that to the gh-pages branch but that might be cool too.

But def. zip it if added to release branch - I think it's ~1900 files already :neckbeard:

**Comment by larsenwork** [comment]
@bollwyvl any thoughts on this?

**Comment by chase** [comment]
Oh, setting it up to push the normal font to gh pages wouldn't be hard either. I can probably get around to it next weekend, if that's alright with you.

**Comment by larsenwork** [comment]
Perfect!
