### ISSUE TITLE
Website: save user options + get statistics of most popular choices

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#27]
So when a user returns the website remembers their last settings. 
- [ ] Garlic

The stats can be used to see which options users prefer and then remove unused option to make room for new options.
- [ ] Keen.io maybe

**Comment by larsenwork** [comment]
The stats could also be used to determine which letters should be default.

**Comment by chase** [comment]
We can use [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) for remembering the options and [Keen.io](https://github.com/keen/keen-js) for analytics.

I've sent the awesome folk at Keen.io an email about setting us up with an OSS project account.

After I get a reply, we can work together on setting up collection and [visualization](https://github.com/keen/keen-js/blob/master/docs/visualization.md#table) of the metrics.

**Comment by larsenwork** [comment]
Sounds great - the data could also make for some good pr at some point :smile:

**Comment by larsenwork** [comment]
Note to self, probably use this: https://github.com/shaneriley/jquery_remember_state

**Comment by chase** [comment]
That definitely would make things easier, @larsenwork's self :stuck_out_tongue:

**Comment by larsenwork** [comment]
Yeah...I once had a teacher that told me laziness is our primary creative muse...

**Comment by larsenwork** [comment]
I found garlic easier to use so I used that instead of jQuery remember state. Plus garlic is just a better name.

**Comment by chase** [comment]
Whatever works, right :smiley:

**Comment by larsenwork** [comment]
Had some issues with garlic so turned it off for now

**Comment by larsenwork** [comment]
Closing this for now - not too many settings for users to click when re-downloading and I just posted a form on twitter to test the format and have gotten 10+ replies in <1hr so might just use that to figure out what people prefer. 
I'm not complaining if someone else adds these features to the website - it's just not a priority for me right now:)
