### ISSUE TITLE
Remove line height options

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#29]
Are they still any editors that doesn't let you set the height manually?

**Comment by olivertaylor** [comment]
Depending on your terminal emulator this can be useful.

**Comment by larsenwork** [comment]
@olivertaylor so there are still terminal emulators where you can't adjust line height independently?

**Comment by chase** [comment]
Indeed. rxvt-unicode for example has options for it, but they rarely work as expected. Also st, http://st.suckless.org

**Comment by larsenwork** [comment]
Ok, keeping the three options then. Closing this for now - can be reopened when/if the download stats makes us wiser.

**Comment by plgruener** [comment]
Just for the record: one cannot change line height in **Eclipse**. (Suggested workaround is to create a new font with desired line spacing and use that one^^). So you may want to keep options to choose from.
