### ISSUE TITLE
Center glyphs in line-height?

### ISSUE THREAD

**Issue by chase** [larsenwork/monoid#32]
![Line height](https://cloud.githubusercontent.com/assets/216803/8174928/e316303a-13b0-11e5-947e-7cf909b38d10.png)

Although this screenshot is from #31, it brings up something that I think should be an easy enough thing to fix.

For those of us using silly things like Airline and Powerline, centering glyphs on the line-height similar to this would be beneficial:
![Mockup](https://cloud.githubusercontent.com/assets/5411/8186709/dcc32ba2-1419-11e5-9481-16f8269ae78f.png)

One wouldn't really notice it if all of the text were on the same background color and the terminal didn't rely on the line-height making the block block, so it isn't super high priority.

**Comment by larsenwork** [comment]
Silly you...but good point, I'll try and adjust the metrics a bit

**Comment by vodik** [comment]
For what its worth, don't worry too much about the blurriness, I'm fairly certain that's my broken fontconfig.

**Comment by larsenwork** [comment]
@vodik ok, report should that not be the case

@chase try these: https://github.com/larsenwork/monoid/tree/master/Testing

**Comment by larsenwork** [comment]
@chase I've tried centring the powerline symbols but unsure if the triangles should be full height (like the branching symbol) or like this:
![screen shot 2015-06-23 at 14 50 31](https://cloud.githubusercontent.com/assets/3859425/8306320/5cd57dde-19b7-11e5-8335-eb79d03b558c.png)

**Comment by chase** [comment]
The triangles should be full height and flush to whatever side opposite to which it points.

**Comment by larsenwork** [comment]
Like so? ![screen shot 2015-06-23 at 20 15 12](https://cloud.githubusercontent.com/assets/3859425/8313772/2c9d9b32-19e5-11e5-8980-49db3aee0811.png)

**Comment by chase** [comment]
Indeed! It looks right, but I'll try it out tomorrow to see if it displays correctly :)

I'll have to add a stretch glyph operation so that line height options also change the Powerline characters, but for now this is great.

**Comment by larsenwork** [comment]
instead of a stretch glyph I can also very quickly make alternates that can be substituted instead if that's easier to code

**Comment by larsenwork** [comment]
closing this as part of cleaning up. @chase feel free to reopen if there's more to look into right now. Height options are part of #48
