### ISSUE TITLE
circleci error message

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#34]
@chase so I originally had this error message:
![screen shot 2015-06-17 at 12 40 38](https://cloud.githubusercontent.com/assets/3859425/8206277/41c7b5f2-14f8-11e5-9d9c-c02dc6ff5c51.png)
I then tried the changing `_release` in build.py to `release` which didn't work 
Reverting to `_release` now gives me this error
![screen shot 2015-06-17 at 13 52 08](https://cloud.githubusercontent.com/assets/3859425/8206302/7f0b6ce2-14f8-11e5-8710-c314226b8b9f.png)

**Comment by larsenwork** [comment]
I'm assuming what I should have done originally wasn't to change build.py but instead line 32 in circle.yml ?

**Comment by chase** [comment]
Actually, neither of those are actually errors.
The first one is just saying that the _release directory it is trying to remove doesn't exist. It is only there should something go wrong.
The second fails because you haven't made any changes to the files in the Source directory.

**Comment by chase** [comment]
For the first error, I'll change it so that it won't appear if it doesn't exist and the "tests" will pass :+1:

**Comment by larsenwork** [comment]
Cheers, I like all green buttons :wink:

**Comment by chase** [comment]
The second error is actually a good thing, if that wasn't clear. It causes the build process to skip any changes you have made that don't actually affect the font. Unfortunately there is no other way to skip builds than failing on a pre-test check.
