### ISSUE TITLE
Make a zip

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#35]
As mentioned in another issue it'd be great to:

- [x] Combine different variations in one zip
- [x] Add a readme.pdf with license in it too (I haven't made this yet)

**Comment by larsenwork** [comment]
@chase: I've now added a readme.pdf (just a copy of readme.md) to the source folder - would be crazy cool if it was included in all them zip files

**Comment by chase** [comment]
That *should* be a quick fix. We'll see if I'm right, haha.

**Comment by chase** [comment]
Oh jeese. I just realized how *HUGE* that Readme.pdf is. 3 MB is a little hefty to be added to every file.

Honest question, could we just use HTML instead?

**Comment by chase** [comment]
I was thinking of using https://github.com/mixu/markdown-styles to generate the HTML.
Then I could make a script that merges all the CSS and inlines the images with https://github.com/jrit/web-resource-inliner

**Comment by chase** [comment]
In the meantime though, I've used markdown-styles to make the HTML, then I opened it up in Chrome removed the padding on the article element, printed it as a PDF, then ran it through smallpdf.com

Same contents but now it only comes in at 161K.

**Comment by larsenwork** [comment]
I just generated it automatically without looking at the size. Agreed it's way to huge. 

Didn't know about markdown styles. Looks great, especially if circleCI could handle it. In the mean time I'd say we just link to the web page to keep things as simple as possible.
