### ISSUE TITLE
Download page is broken

### ISSUE THREAD

**Issue by busla** [larsenwork/monoid#38]
This url: 
https://raw.githubusercontent.com/larsenwork/monoid/release/Monoid-loose.ttf.zip?raw=true 

is not found

**Comment by larsenwork** [comment]
yep, @chase is currently improving the build scripts - maybe do that to a `release2` folder until stable? 
I've just pushed an update that should be in the release folder in a couple of minutes.

**Comment by larsenwork** [comment]
Should work again now, thanks for the heads up :+1:
