### ISSUE TITLE
Any reason to use rawgit over just raw.githubusercontent.com

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#39]
@chase 

https://github.com/larsenwork/monoid/blob/gh-pages/index.html#L1042 - I changed it just to test and seems to be working just fine.

**Comment by chase** [comment]
[RawGit](http://rawgit.com/): "Files are served via MaxCDN's super fast global CDN."

Also so that Monoid doesn't get blacklisted for serving binary files from a Repo.

**Comment by chase** [comment]
Also, why not set the Download link here?
https://github.com/larsenwork/monoid/blob/gh-pages/index.html#L1110

Something like:
```javascript
$('#download').attr('href',FontName);
```

That would allow people to copy the link to share with others.

**Comment by chase** [comment]
@larsenwork Basically, using githubusercontent.com is bad for Monoid longterm. It is also slower. Using the CDN means that everyone across the world gets equal download speeds, basically.

**Comment by larsenwork** [comment]
Ok, switched back - just did it as part of debugging this morning :smile: 

Download link - I want people to share larsenwork.com/monoid instead of direct links since they change when we make changes to build.py so to avoid future 404's...

**Comment by chase** [comment]
Maybe setup a way to share option choices then?
