### ISSUE TITLE
Add bold + oblique to the website

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#42]
- [x] Update build script to send all monoid's to the webpage too
- [x] Update webpage to use the oblique + bold version in code previews

**Comment by larsenwork** [comment]
@chase seems like the updated script removed ttf from the mix? Currently woff2, woff and eot only :smile:

**Comment by chase** [comment]
![DOH!](http://blogs.telegraph.co.uk/news/files/2013/07/homer-simpson-doh.jpg)

**Comment by chase** [comment]
Okay, _should_ be fixed now.

**Comment by larsenwork** [comment]
This is done :smile:
