### ISSUE TITLE
Issues with the updated build script

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#45]
I tried commenting out the [calt-thingy](https://github.com/larsenwork/monoid/blob/master/Scripts/build.py#L50) just to get a release through but it also failed. 
```
! git diff `git log -1 --pretty='%B' release | cut -d ' ' -f 4` --name-only --exit-code Source

! git diff `git log -1 --pretty='%B' release | cut -d ' ' -f 4` --name-only --exit-code Source returned exit code 1

Action failed: ! git diff `git log -1 --pretty='%B' release | cut -d ' ' -f 4` --name-only --exit-code Source
```

**Comment by chase** [comment]
As before, this just means you haven't made any changes to the Source files.

**Comment by chase** [comment]
https://github.com/larsenwork/monoid/blob/master/circle.yml#L13-L14

**Comment by chase** [comment]
Disabled the check for now, doing a trial build to see if we can't get Downloads back up.
