### ISSUE TITLE
Download currently not working

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#46]
We are experimenting with parallel build scripts and other stuff - will be up again this afternoon (hopefully) :smile:

**Comment by chase** [comment]
Woah, this definitely should NEVER happen. Looking into it now.

**Comment by chase** [comment]
What I need to do this weekend is set up the push as a deploy step, that way if any of the stages fail it will NOT try pushing.

**Comment by chase** [comment]
Fixed the build. Sorry for the interruption!

**Comment by chase** [comment]
Need to flush the release branch.

**Comment by larsenwork** [comment]
ok, how do we do that ? :smile:

**Comment by chase** [comment]
Doing that right now.

**Comment by larsenwork** [comment]
Cheers, I'm holding off on pushing until I get a "all clear" :sunglasses:

**Comment by chase** [comment]
ALL CLEAR!
![Keep Calm, I am all clear](http://sd.keepcalm-o-matic.co.uk/i/keep-calm-i-am-all-clear.png)
