### ISSUE TITLE
Only keep last 2 releases

### ISSUE THREAD

**Issue by chase** [larsenwork/monoid#47]
Anything more than that is putting a lot of load on Github and CircleCI. They are generous as it is not to give a cease and desist :smile:

**Comment by larsenwork** [comment]
aren't we only keeping the latest release?

**Comment by chase** [comment]
Nope! Each commit means that _any_ object in the Git repository's history remains, `git rm` only removes for a commit, not the Git index.

**Comment by chase** [comment]
For example, the PDF screw-up (3 MB, yikes) left the release branch at over 2 GB.

**Comment by chase** [comment]
I worked with the CircleCI folk to cleanup the source cache and I'm setting it up so that the release branch only ever contains a single actual release.

**Comment by larsenwork** [comment]
ah - I thought we did that already because last time the release branch was inadvertently empty there was no "history" - i.e. no commit I could revert to.

**Comment by chase** [comment]
Nope, there has always been several dozen commits. Even when it is "empty" there are 2 commits. The initial history then a quick fixup to the .gitignore file.

Now I'm resetting to that 2nd commit before commit.
