### ISSUE TITLE
circleci updating frameworks

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#49]
@chase Not sure if this affects us but:

Hi Andreas,

We're planning on shipping some changes to our container images. We will ship the changes between the 27th and the 31st of July.

Below is the list of packages that will be upgraded.

Major changes

These changes may break your builds. Please check them and prepare for the changes in advance.

Chrome: 38 => 43
ChromeDriver: 2.12 => 2.16
Docker: 1.4 => 1.6.2*

Minor changes

These upgrades don’t include any breaking changes, but they are worth mentioning.

Cassandra: 2.1.5 => 2.1.7
heroku & heroku-toolbelt: 3.37.6 => 3.39.1
npm: 2.11.1 => 2.12.0
pip: 7.0.3 => 7.1.0
neo4j: 2.2.2 => 2.2.3
virtualenv: 13.0.3 => 13.1.0

New packages

OpenJDK 8
Android ABI including Google APIs, API levels 21 & 22

  * We upgraded Docker to 1.6.2 a week ago for eveyone as a temporary measure to follow Docker Hub API change. In this image update, we will pre-install Docker 1.6.2 in the containers and use it as default Docker version.

**Comment by chase** [comment]
This more than likely won't affect us. Thanks for the heads up though! :+1:

**Comment by larsenwork** [comment]
:+1:
