### ISSUE TITLE
Improve rendering without antialiasing

### ISSUE THREAD

**Issue by zevv** [larsenwork/monoid#5]
Hi,

I've been running my own custom font for the last ten years, but I guess your font might make for a nice alternative.

I'm not fan of antialiasing for programming fonts though, but I can't get Mono16 to render properly on sizes other then 16px. Am I doing something wrong, or does your font not (yet?) include rendering hints for other pixel sizes?

Thanks,

**Comment by andreaslarsen** [comment]
It is autohinted so it should work at all sizes but it's drawn over a 16pt grid so that bitmap-looking sharpness is only at 16. 

But it's difficult for me to determine if it's a bug without a screenshot :)

**Comment by zevv** [comment]
Using xterm, settign font size and disabling antialiasing:

```
xterm -fa 'Mono16:pixelsize=24:style=Normal:antialias=false'
```

Results for 14, 16 and 24:

http://zevv.nl/div/14.jpg
http://zevv.nl/div/16.jpg
http://zevv.nl/div/24.jpg

**Comment by andreaslarsen** [comment]
Yep, as expected - the autohint doesn't really work without antialiasing - the reason it looks good enough at 16 pt is because it's drawn over a 16pt grid.

I only started drawing font's <½ year ago as a hobby so I'm not that experienced but achieving pixel perfect look without antialiasing at all font sizes sounds like a lot of work and not something I will look into but if you or someone else seeing this feels like it then by al means give it a go ;)

**Comment by zevv** [comment]
* On 2015-04-06 21:12:17 +0200, Andreas Larsen wrote:
 
> Yep, as expected - the autohint doesn't really work without
> antialiasing - the reason it looks good enough at 16 pt is because
> it's drawn over a 16pt grid.
> 
> I only started drawing font's <½ year ago as a hobby so I'm not that
> experienced but achieving pixel perfect look without antialiasing at
> all font sizes sounds like a lot of work and not something I will look
> into but if you or someone else seeing this feels like it then by al
> means give it a go ;)

I can't blame you, making fonts is a tedious job, and it's hard to
figure out all the technical details and font-lingo to get things to
work right on various platforms.  I've been running my own font for a
decade or so, but it's a bitmap font instead of truetype:

http://zevv.nl/play/code/zevv-peep/

I was hoping to find a replacement TTF that would work properly on more
platforms one day, and yours comes quite close to that. 

It's just a tad to big to my liking. With modern computer screens
getting wider and wider, vertical screen space is becoming a scarse
resource. Having 16 px lines instead of the 14 px I'm used to is like
going from a 1280 to a 1050 lines display; i'm losing a lot lines in the
process!

I'll try to fiddle with the various geometry parameters in a font editor
to see if I can get Mono16 to squeeze into my requirements, thanks for
the support so far.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by andreaslarsen** [comment]
That font looks really nice! When the build script that another guy is working on is done it will probably support adjusting line hight too ;) 
And I actually think I'll make some changes to mono16 inspired by your font to make it a bit less tall...

**Comment by andreaslarsen** [comment]
![screen shot 2015-04-07 at 10 45 18](https://cloud.githubusercontent.com/assets/3859425/7019713/3bf4c4ca-dd13-11e4-8a38-8ef699957637.png)

**Comment by andreaslarsen** [comment]
![screen shot 2015-04-07 at 13 10 40](https://cloud.githubusercontent.com/assets/3859425/7022004/90de24c2-dd27-11e4-8089-94055731aa3e.png)

**Comment by zevv** [comment]
Looks a bit more compact, you reduced the line spacing here? 


* On 2015-04-07 13:11:17 +0200, Andreas Larsen wrote:
 
> ![screen shot 2015-04-07 at 13 10 40](https://cloud.githubusercontent.com/assets/3859425/7022004/90de24c2-dd27-11e4-8089-94055731aa3e.png)
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/andreaslarsen/mono16/issues/5#issuecomment-90508726

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by andreaslarsen** [comment]
I'm using brackets where you set the line height in css but I've reduced the length of the ascenders and descenders to allow for smaller line heights without the text overlapping

**Comment by larsenwork** [comment]
I'm not sure this issue is something I'll look into - if/when someone else does please reopen :+1:
