### ISSUE TITLE
font names are not set correctly

### ISSUE THREAD

**Issue by akorobov** [larsenwork/monoid#50]
Thank you for awesome font! Installing fonts downloaded from webpage on osx (10.11) result in Font Book marking them as duplicates because style names for regular/oblique/bold are all set to 'halftight' (option chosen during download):

<img width="788" alt="screen shot 2015-07-17 at 6 50 32 am" src="https://cloud.githubusercontent.com/assets/102709/8749147/6c851244-2c54-11e5-852e-7409d6241ebf.png">

**Comment by chase** [comment]
I'll look into this tomorrow. Thanks for bringing this to our attention!

**Comment by larsenwork** [comment]
@akorobov @chase :+1: 
It's something down here that needs fixing: https://github.com/larsenwork/monoid/blob/master/Scripts/fontbuilder.py#L169

Should be "Monoid HalfTight Oblique" I think.

**Comment by larsenwork** [comment]
This: https://github.com/larsenwork/monoid/commit/de20501faf3b72f72574aaa7b1c97e4a57eea085 should be merged with gh-pages once this https://github.com/larsenwork/monoid/commit/95f874112b38e21cf4d26caf011be04273eeb30c is included together with a fix for this issue.

**Comment by larsenwork** [comment]
:+1: It wasn't possible to add the name change to the family name instead? I could foresee some potential problems with e.g. editors and VIMs not being able to guess what bold and oblique version to use.

![screen shot 2015-07-19 at 12 24 05](https://cloud.githubusercontent.com/assets/3859425/8765553/416a1686-2e11-11e5-9fb7-a846dba54a89.png)

**Comment by larsenwork** [comment]
What we have now
```
Fontname: Monoid-Oblique-Tight
Family Name: Monoid
Name for Humans: Monoid Oblique Tight
```
What I think is preferable
```
Fontname: Monoid-Tight-Oblique
Family Name: Monoid Tight
Name for Humans: Monoid Tight Oblique
```

**Comment by chase** [comment]
There shouldn't be any problems for most editors, but then again I'm pretty tired.
The original issue was for font duplication issues. This addresses it without rewriting a lot of code.

Your suggestions belong in another issue as it is another task entirely.

**Comment by larsenwork** [comment]
@chase ok, it's still the same issue though since the naming is still technically not set correctly. No reason to create more issues :smile: 

In e.g. Atom editor you set the family name and then it automatically picks bold and oblique from there meaning in the current state you can't use anything but the default width.
![screen shot 2015-07-19 at 12 55 48](https://cloud.githubusercontent.com/assets/3859425/8765647/e348fba8-2e15-11e5-8ee5-16c1bc7bf63d.png)
