### ISSUE TITLE
Bitmap version

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#53]
Not something I can allocate the time to do right now - but others can look into it. Sourcetree is acting up right now but in my next push there'll be a monoid-bitmap.sfdir in utillities/wip'n'test

**Comment by dbb** [comment]
[Seconded!](https://www.reddit.com/r/typography/comments/3dqzyl/designing_a_coding_font_part_1_a_short_article_i/ct8dcdw?context=1)

**Comment by larsenwork** [comment]
All the characters have been autogenerated in the [monoid-bitmap.sfdir](https://github.com/larsenwork/monoid/tree/master/Utilities/WIP'n'test/Monoid-Bitmap.sfdir) so it's just a matter of fixing some quirks
![screen shot 2015-07-19 at 12 50 29](https://cloud.githubusercontent.com/assets/3859425/8765623/e47d0768-2e14-11e5-8673-5e3f36454495.png)

**Comment by larsenwork** [comment]
From the main window in FontForge you just select a glyph that needs adjustment and press ctrl+j to open bitmap editor window. 
Select the pen from the toolbar and use it to add/remove dots.
@dbb feel free to get started. I quickly went through the uppercase + the first lowercase letters

**Comment by larsenwork** [comment]
not something I'll pursue further - feel free to reopen and/comment if you want to contribute
