### ISSUE TITLE
Set Font, Full, and Family Name

### ISSUE THREAD

**Issue by chase** [larsenwork/monoid#54]
@larsenwork:

> What we have now
> ```
Fontname: Monoid-Oblique-Tight
Family Name: Monoid
Name for Humans: Monoid Oblique Tight
```
> What I think is preferable
> ```
Fontname: Monoid-Tight-Oblique
Family Name: Monoid Tight
Name for Humans: Monoid Tight Oblique
```

Easiest is ignoring the base font's Font/Full name entirely.
New Family Name: `{Base Family} {Variation}`
New Full Name: `{Base Family} {Variation} {Base Subfamily/Style} {Options}`
New Font Name: `{Base Family}-{Variation}-{Base Subfamily/Style}-{Options}`

**Comment by chase** [comment]
This will take about 3 hours of effort to rewrite, so I probably won't get this done this weekend.

**Comment by larsenwork** [comment]
Ah didn't see this before commenting on:
https://github.com/larsenwork/monoid/issues/50#issuecomment-122649248
No stress

**Comment by larsenwork** [comment]
I don't think the options should be in the font name though, or? 
99% will download one version (options) and use that and adding the options to the font name will create really long names.
```
New Family Name: {Base Family} {Variation}
New Full Name:   {Base Family} {Variation} {Base Subfamily/Style}
New Font Name:   {Base Family}-{Variation}-{Base Subfamily/Style}
```

**Comment by chase** [comment]
Probably a better idea that way, now that I think about it. Shame I didn't have a lot of time this weekend, especially since you've gained so many more stars!
Who knows, maybe one of them can pitch in a patch before me :+1:

**Comment by larsenwork** [comment]
*we've gained so many more stars :wink: 
You're also forgetting to update the fontlog when you add stuff...

**Comment by chase** [comment]
True... I just feel like my work on the CI is never done, so it isn't worthy of having a version number yet :stuck_out_tongue:

**Comment by larsenwork** [comment]
Things doesn't have to have a version number to be in the log though :)

**Comment by larsenwork** [comment]
![screen shot 2015-07-22 at 18 27 28](https://cloud.githubusercontent.com/assets/3859425/8830942/6563f2d8-309f-11e5-928a-adea2d0314fe.png)

:+1:
