### ISSUE TITLE
Add social/media icons

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#55]
There's a svg, illustrator and affinity designer template here: https://github.com/larsenwork/monoid/tree/master/Utilities/Graphics

I just need a svg similar to `twitterIcon.svg` and I can easily import it to the font.

Please use lower case for the names (and icon with capital "I) e.g. `youtubeIcon.svg`

**Comment by plgruener** [comment]
The `downloadIcon` in the live-preview on the website does not work with the alternate l enabled. It works however in the installed font (version 0.55).

**Comment by larsenwork** [comment]
Yep, that's because I've only enabled it for the default l. 
When you download alt l the change is hardcoded so alt l = normal l. 
I could make it work with both l's though.

**Comment by larsenwork** [comment]
Closing this and moving icons to Monoisome :smile:
