### ISSUE TITLE
Circleci seems to run with every push

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#57]
@chase Didn't we have "only run when changes are made to the source folder" working at some point or am I mistaken?

It's currently running even if it's just gh-pages being updated
![screen shot 2015-07-21 at 12 20 25](https://cloud.githubusercontent.com/assets/3859425/8798515/16bf2708-2fa3-11e5-9e11-59c79c0f2bd1.png)

**Comment by chase** [comment]
We did, but I disabled it because you were annoyed that it came up with this error:
![Error](https://cloud.githubusercontent.com/assets/3859425/8206302/7f0b6ce2-14f8-11e5-8710-c314226b8b9f.png)

**Comment by chase** [comment]
Regarding the `gh-pages` thing, it isn't actually running tests thus the red `No Tests` label. It is taking up queue time because for some damn reason it is fetching the source cache and blocking actual builds.

I have a solution in mind, let me whip something up on my personal branch.

**Comment by larsenwork** [comment]
Cheers.

Could a simple (?) solution be to have a boolean variable in build.py called `runCircleCI` or something similar. So that circleci only builds when that's true and a build obviously changes the value from true to false?

**Comment by chase** [comment]
The simplest solution would be to just un-comment the code you see above.
I'm going to put it in a file with a name that should make it more clear what it is doing, that way nobody gets confused about that really long error, haha.

I'm also making it so that the `release` branch isn't cached and is actually pushed off of a template branch. This will prevent the wait after I rebuild without the cache.

**Comment by larsenwork** [comment]
:clap:

**Comment by chase** [comment]
Also just figured out a way to not rely on prior release markers for Source changes, so that'll make things even quicker.

**Comment by chase** [comment]
So far we're down to 11:32 and better change checks. Not sure if that will be consistent, since CircleCI is STILL pulling a branch I tell it to ignore.
