### ISSUE TITLE
Difference between Normal and Loose styles?

### ISSUE THREAD

**Issue by zevv** [larsenwork/monoid#6]
Hi,

For some reason the Normal and Loose styles render the same for my terminal, see the screenshots at:

```
xterm -fa 'Mono16:pixelsize=16:style=Loose'
xterm -fa 'Mono16:pixelsize=16:style=Loose'
xterm -fa 'Mono16:pixelsize=16:style=Loose'
```

http://zevv.nl/div/mono16-loose.png
http://zevv.nl/div/mono16-normal.png
http://zevv.nl/div/mono16-tight.png

```
$ fc-list  | grep Mono16
/usr/local/share/fonts/truetype/mono16/Mono16-Tight.ttf: Mono16:style=Tight
/usr/local/share/fonts/truetype/mono16/Mono16-Loose.ttf: Mono16:style=Loose
/usr/local/share/fonts/truetype/mono16/Mono16-Normal.ttf: Mono16:style=Normal
```

**Comment by andreaslarsen** [comment]
That is very strange, I haven't used any "tricks" or anything that could explain that. I've used UPM 2048 and Glyphs in loose are 1152 wide and regular 1024. 
I assume it's displaying correctly in other programs?
What terminal are you using?

**Comment by zevv** [comment]
* On 2015-04-06 15:46:02 +0200, Andreas Larsen wrote:
 
> That is very strange, I haven't used any "tricks" or anything that could explain that. I've used UPM 2048 and Glyphs in loose are 1152 wide and regular 1024. 
> I assume it's displaying correctly in other programs?
> What terminal are you using?

I tried in urxvt, rxvt and xterm, all with similar results. The funny
thing is that if I install only the Loose font, it still renders like
the Normal in your screenshot. Ill compare in more detail when I'm back
t my PC.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by andreaslarsen** [comment]
Ok, I have an idea if your further inspection doesn't explain it

**Comment by zevv** [comment]
* On 2015-04-06 17:47:06 +0200, Andreas Larsen wrote:
 
> Ok, I have an idea if your further inspection doesn't explain it

I just pasted one of your example snippets in xterm with only the Loose
font installed, but it renders exactly similar to the Normal type
instead.

http://zevv.nl/div/normal-or-loose.png

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by andreaslarsen** [comment]
and this is the latest version (0.23 Loose, 0.24 Normal - not that I've changed anything but just to make sure we're not beating a dead horse)

**Comment by zevv** [comment]
* On 2015-04-06 18:41:59 +0200, Andreas Larsen wrote:
 
> and this is the latest version (0.23 Loose, 0.24 Normal - not that
> I've changed anything but just to make sure we're not beating a dead
> horse)

Original problem showed with 0.22, but still persists with 0.23.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by andreaslarsen** [comment]
Try this: https://github.com/andreaslarsen/mono16/blob/master/Resources/Testing/LooseTest.ttf?raw=true

**Comment by chase** [comment]
@zevv I'm not sure if this was simply a typo, but if you ran screenshots for
```
xterm -fa 'Mono16:pixelsize=16:style=Loose'
xterm -fa 'Mono16:pixelsize=16:style=Loose'
xterm -fa 'Mono16:pixelsize=16:style=Loose'
```
Then the results would all be the same, as the style is set to Loose for all of them.

**Comment by zevv** [comment]
* On 2015-04-16 05:09:37 +0200, Chase Colman wrote:
 
> @zevv I'm not sure if this was simply a typo, but if you ran screenshots for
> ```
> xterm -fa 'Mono16:pixelsize=16:style=Loose'
> xterm -fa 'Mono16:pixelsize=16:style=Loose'
> xterm -fa 'Mono16:pixelsize=16:style=Loose'
> ```
> Then the results would all be the same, as the style is set to Loose for all of them.

That was indeed a typo, but thanks for noticing!

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by andreaslarsen** [comment]
@zevv try the updated fonts from http://andreaslarsen.github.io/monoid/ - how do they look?
