### ISSUE TITLE
Getting opentype features working reliably

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#60]
I'm haven't been able to get the #56 working and ligatures are still buggy (some work and some doesn't) #25 

I'm trying to figure out if this is a fontforge issue and if so then maybe using afdko as suggested here: http://typedrawers.com/discussion/1029/class-based-contextual-positioning-how-to

**Comment by pauldhunt** [comment]
do let me know if you need help setting things up for FDK. are you mainly using fontforge for development?

**Comment by chase** [comment]
We are using FontForge primarily, yes.

**Comment by larsenwork** [comment]
@pauldhunt thanks for offer to help - I'm currently trying to see if I can get it working without FDK (i.e. using FontForge only) as that would add another step to the build process. 

What we're currently doing is 
1) Push a source change (sfdir) 
2) CircleCi runs the FontForge building scripts generating the 3200 combination options

So makeOTF would have to run through 3200 font files which I'd imagine would take some time

**Comment by chase** [comment]
makeOTF shouldn't be too slow, considering we also run zip on 3200*5 files :+1:

**Comment by larsenwork** [comment]
Looks like it was maybe down to a small error in the .fea file and it's now working. Keeping fingers crossed and this open for a while.

**Comment by larsenwork** [comment]
Seems to work so closing this for now. @pauldhunt thanks for the offer to help - I might take you up on that another time :smile:
