### ISSUE TITLE
Display on Retina Screen Thin, Display on Other Monitors Good

### ISSUE THREAD

**Issue by mikebronner** [larsenwork/monoid#62]
i noticed that Monoid appears very thin when viewed on a retina monitor, like the 2015 retina iMac. (Also, I am running OS X "El Capitan" Public Beta 2, and there are some font issues in this build, so it may be related to that, not sure. Unfortunately I don't have another retina mac to test this on.)

I seem to have a harder time reading the thin retina version all day long. The non-retina version seems to flow much better. (I was using Monaco prior to switching to Monoid, because it had more substance to it than other developer fonts seemed to have.)

To illustrate the difference, I took a pic of the same text on retina and on normal using my iPhone (just to be clear if there are any technical ramifications):

Non-Retina:
![img_0748 1](https://cloud.githubusercontent.com/assets/1791050/8878321/39ae8e96-31df-11e5-9a1a-add4b1e79273.JPG)

Retina:
![img_0747 1](https://cloud.githubusercontent.com/assets/1791050/8878322/39c13726-31df-11e5-8798-5889c56fc783.JPG)

(Not sure why the previews are upside down.)

**Comment by larsenwork** [comment]
Not much I can do about the thinness as different displays renders font differently. I know some retina users prefer to have dark background and bright text as it makes it appear a bit thicker.

Could you elaborate a bit on what you mean by flow?

**Comment by mikebronner** [comment]
Sorry to not have been more clear on "flow" :) 

Basically the legibility, the flow of the eye across the page. Tall, thin letters make the eye stop more, while broader, more proportional letters help the eye move across the page. (I know you know all this already, just elaborating on what I was referring to.)

I have astigmatism, so I need to pick fonts carefully to be as legible as possible to avoid eye strain.

**Comment by larsenwork** [comment]
Thanks - letters are deliberately narrow and with loose tracking to make it easier to see the individual letter (when e.g. typing and to avoid typos).
What I'm not sure I'm understanding is how the regular version flows better than the retina as you mentioned originally?

**Comment by mikebronner** [comment]
Because the non-retina screens render the body of the letters thicker, that's the only difference I could tell. :)

**Comment by larsenwork** [comment]
Ah....non-retina **screens** :smile: 
I thought you were comparing monoid-retina vs monoid-regular. 

Let me just try something.

**Comment by mikebronner** [comment]
Ah LOL sorry for the confusion, hehe :)

**Comment by larsenwork** [comment]
Hehe...that's exactly what I'm thinking - so you can choose between how thick you want regular to be.

Choosing the thicker on low res would obviously mean => less sharp. But could work well on hdpi displays. 

This is not something that'll happen soon but I'll upload two slightly thicker versions soon that you can try to see if there is any gain/point in doing it.

**Comment by mikebronner** [comment]
Also, for some reason my IDE (PHPStorm 9) doesn't let me select a variant for the font, I can only choose the font family. Perhaps its using Retina, instead of Regular? I could try uninstalling the Retina variant and see if that helps?

**Comment by larsenwork** [comment]
Try this: https://github.com/larsenwork/monoid/blob/master/Utilities/WIP'n'test/MonoidTest-Retina.ttf?raw=true

**Comment by mikebronner** [comment]
Thanks Andreas! :)

Here is a screenshot of the results. Are these expected? I'm not sure if I can see a rendering difference. And anyone else on Retina screens confirm this? I wonder if the El Capitan Public Beta 2 just has 2 many font issues and issn't rendering the font as intended?

<img width="840" alt="screen shot 2015-07-24 at 5 30 20 pm" src="https://cloud.githubusercontent.com/assets/1791050/8887098/855e8760-322a-11e5-8685-25f6b0f55772.png">

**Comment by mikebronner** [comment]
Conversely, this may be due to the Java rendering of the font in PHPStorm? Because it seems to me the standard Retina variant when previewed in FontBook does not look as thin as rendered in PHPStorm.

**Comment by larsenwork** [comment]
looks about right (it's thicker) - try it at coding sizes

**Comment by foucist** [comment]
Retina & Yosemite here, it definitely looks very thin on the http://larsenwork.com/monoid/ page.  Once I installed it, I realized it looks thinner because it's slightly taller than I'm used to.  Monoid @ 14pt is nearly an exact match to match to my current font, Panic Sans (modified Bitstream Vera Sans) @ 12pt, same amount of lines & columns in terminal.  BTW, I took screenshots of my terminal with Monoid Retina & MonoidTest Retina, and there's zero difference.

**Comment by mikebronner** [comment]
@foucist Thanks for testing that -- so you would leave with the conclusion that it gets thinner at larger sizes? I use 22px for my IDE.

**Comment by Fequois** [comment]
@mikebronner This is interesting! I also have pretty bad astigmatism in both eyes, and I actually find this font legible for the exact reason you're not! I love the light thickness and loose spacing. Then, like @larsenwork mentioned as well, I am indeed using a dark colour syntax. Normally I bump up the font size to a beastly number, but not with this one.

Haven't tried it at larger sizes than 15px, but I am using the Retina variant on my rMBP. Will check on my retina iMac as well once I get it set up again. (Just moved, so your issue might be solved before I have time.)

<img width="568" alt="screen shot 2015-07-29 at 13 04 00" src="https://cloud.githubusercontent.com/assets/3535255/8956927/5a8482bc-35f2-11e5-838e-b30aacdb4807.png">

**Comment by larsenwork** [comment]
@Fequois cheers, glad you liked it. 

I've added adding a thicker weight (and probably changing the current to "book" weight on the roadmap so it'll happen someday.

Just to clarify if anyone gets confused about the sizes: I've just changed it so 15px old = 12px new.

**Comment by larsenwork** [comment]
@Fequois that __ should be a ligature...I'll add a screenshot to #25 soon :neckbeard:

**Comment by Fequois** [comment]
@larsenwork Love it.

My build of `Monoid-Retina.ttf` is from 27 July at 00:06. Is that before or after you added those ligatures? I'll fetch a new copy from the build repo in any case.

**Comment by larsenwork** [comment]
@Fequois haven't added them yet. "Should" as in: "Hey they look a bit *meh* and can be improved" :wink:

**Comment by Fequois** [comment]
@larsenwork Ah, I suspected that might be the case.

Didn't hurt to update to today's build anyway. :smile:

**Comment by larsenwork** [comment]
I'm closing (too thin) this as I've added creating a thicker version to the roadmap. I'll reopen this issue once I start looking into it.

**Comment by mikebronner** [comment]
@Fequois That makes sense, as light will look bolder on dark background, while dark will look thinner on light background.

@larsenwork I wonder if I goofed up while installing the fonts. I installed Regular, Oblique, Bold, and Retina. I wonder if PHPStorm is choosing Retina over Regular. I will try with Retina variant removed when I get back to the office tomorrow.

**Comment by larsenwork** [comment]
@mikebronner retina should look better on a retina screen (better spacing), no difference in thickness

**Comment by mikebronner** [comment]
@larsenwork Thanks for the clarification. :)
