### ISSUE TITLE
Adding version number to zip file to update rawgit

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#64]
So it's e.g. `Monoid-0-1-3-NoCalt-v0.50.zip` instead of `Monoid-0-1-3-NoCalt.zip` otherwise rawgit isn't updated :scream: :smile:

**Comment by chase** [comment]
Huh, that's strange that RawGit doesn't propagate correctly.

**Comment by larsenwork** [comment]
no - I think it's by design if you read the description on their website. I just hardcoded v.0.52 now - not too much trouble actually so not sure if we should do anything more about it.
Version-number just needs to be updated
1. In fonts
2. In zip script
3. On the webpage

**Comment by chase** [comment]
Ah, you're right: "Permanently caches after first request."

I have a better idea than using a version number, I can just add a file `version.js` to gh-pages containing that sets `window.MONOID_RELEASE` to the release commit hash in the gh-pages step.

That way you don't have to manually set a new version every damn time.

So basically the URL would become:
``` javascript
'https://cdn.rawgit.com/larsenwork/monoid/' + window.MONOID_RELEASE + '/Monoid' + options + '.zip'
```

Instead of :
``` javascript
'https://cdn.rawgit.com/larsenwork/monoid/release/Monoid' + options + '.zip'
```

**Comment by chase** [comment]
RawGit even says:
> It's best to use a specific tag or commit hash in the URL (not a branch). Files are cached permanently after the first request.

Silly that I didn't pay attention to this earlier.

**Comment by larsenwork** [comment]
No worries, it works now :smile: 

`version.js` could be great to have

**Comment by chase** [comment]
Something you are doing with Cloudflare and GitHub pages is causing `larsenwork.com/monoid/js/release.js` to get a 404. Any ideas?

**Comment by larsenwork** [comment]
no, but clearing the cache is my go to thing when having issues...two sec

**Comment by larsenwork** [comment]
did it help?

**Comment by larsenwork** [comment]
I can put the caching in dev mode if you're trying things out?

**Comment by chase** [comment]
Hm, since `release` needs to NOT be cached how about you set up a CloudFlare page rule for `/monoid/js/release.js` with Custom caching set to `Bypass cache`?

**Comment by chase** [comment]
I'm not trying things out. The fix went live, but CloudFlare wasn't picking up until you manually purged the cache. I made an emergency patch to use the RawGit testing URL, but that's a no-go in the long term.

**Comment by larsenwork** [comment]
like this? 
![screen shot 2015-07-24 at 22 52 01](https://cloud.githubusercontent.com/assets/3859425/8884384/a40f8430-3256-11e5-9a66-16d0b501a949.png)

**Comment by chase** [comment]
That *should* do it.

**Comment by larsenwork** [comment]
Hehe...I'm not feeling overly audacious right now either - but things look like they're working and we are :rocket: to the :star2: so we must be doing something right.
![c7c](https://cloud.githubusercontent.com/assets/3859425/8884595/43e100f0-3258-11e5-9c4f-74b953cebf13.jpg)
