### ISSUE TITLE
Monoid-HalfTight-Small.zip 

### ISSUE THREAD

**Issue by nathanhere** [larsenwork/monoid#65]
Attempting to download from https://cdn.rawgit.com/larsenwork/monoid/release/Monoid-HalfTight-Small.zip leads to a 404 Error.

**Comment by chase** [comment]
Thanks for reporting it! Right now we are making some changes to how releases are handled, sorry for the inconvenience.

**Comment by larsenwork** [comment]
Try reloading the page. I have purged the cache but you might have a local copy in your browser.

**Comment by nathanhere** [comment]
Ah still get the 404 message (just tried a different browser--IE instead of Chrome).

**Comment by chase** [comment]
@nathanhere I just made some changes.
Could you try using the web page to select your options and download again?

**Comment by nathanhere** [comment]
Both web page and direct nav work! :)

**Comment by chase** [comment]
Cheers!
