### ISSUE TITLE
Add editor support to readme

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#67]
Please add your findings to the readme (if your editor isn't already on the list).

**Comment by santosh** [comment]
How to confirm it's working?

**Comment by santosh** [comment]
And how to tell if it's partially working?

**Comment by santosh** [comment]
Are you targeting whole family editors? Please note this includes all the editors including word processors. Or are you just talking about text-editor/code-editing softwares?

**Comment by larsenwork** [comment]
Not sure about partially - might just remove it and then add it if the case appears :)

**Comment by santosh** [comment]
I think partially was good. Are you sure you want to merge *partly working* with *not working*? :confused:

**Comment by larsenwork** [comment]
@santosh do you have any examples of partly working?

**Comment by santosh** [comment]
Actually yes!

Not all ligatures are working fine here!

![image](https://cloud.githubusercontent.com/assets/1515991/8912453/86a6f5e8-34b0-11e5-99e5-c364cafc7dd3.png)

**Comment by larsenwork** [comment]
@santosh that is definitely none of the ligatures working :)
gVim is already on the not working list

**Comment by santosh** [comment]
As far as I can see, **less than or equal**  is working!

**Comment by plgruener** [comment]
But in a wrong way: the < gets invisible, and = gets expanded to the <= ligature. Try deleting it again, you'll notice the bug.

**Comment by larsenwork** [comment]
what @plgruener said. "less than or equal" get's displayed all over the place.

"Partly working" is currently a hypothetical scenario so I see no reason to add it until it appears :)

**Comment by larsenwork** [comment]
Adding a "please add your findings" comment directly in the readme so closing this
