### ISSUE TITLE
Protocol specifier gets offset too much by double slash ligature

### ISSUE THREAD

**Issue by p-e-w** [larsenwork/monoid#68]
Screenshot from "swift" demo on http://larsenwork.com/monoid/:

![Screenshot](https://cloud.githubusercontent.com/assets/2702526/8888404/0e1869f0-32ac-11e5-8e46-62792876697a.png)

You can see that the double slash ligature pulls a little too far to the right, visually disturbing URLs. This does not happen with e.g. the `->` ligature, which remains perfectly centered within its space.

Incidentally, I would also argue that the single slash after ".com" cuts the `m` a little too closely.

**Comment by larsenwork** [comment]
https://github.com/larsenwork/monoid/issues/25#issuecomment-124777220 :wink: 

About the m then it could be something I could fix with #56

**Comment by p-e-w** [comment]
Thanks, didn't see that comment. You can close this issue if you like.
