### ISSUE TITLE
Visual Studio 2010. 

### ISSUE THREAD

**Issue by przemekwa** [larsenwork/monoid#71]
I want to use MonoId with Visual Studio 2010 and i have problem with "t" letter.  Is this "t" letter is ok.  

![image](https://cloud.githubusercontent.com/assets/5380497/8901756/9b63f356-344b-11e5-8bbe-066e16e35437.png)

or I do something wrong because the font is not really good to read.

**Comment by larsenwork** [comment]
Try reducing the font size. It's designed for 15px but what that is in points depends on your screen/OS settings.

**Comment by larsenwork** [comment]
closing this: related to #81 
@przemekwa try https://dl.dropboxusercontent.com/u/3019777/Monoid-Regular.ttf at 12pt and let me know in #81 how it goes
