### ISSUE TITLE
cannot see regular font on Windows 7

### ISSUE THREAD

**Issue by axd1967** [larsenwork/monoid#72]
Tried to install the four fonts (bold, oblique, regular, retina) from http://larsenwork.com/monoid/ on Windows 7, but I can see only bold and oblique.

smells like related to #23 and maybe #22

**Comment by ElectronicWar** [comment]
Same behaviour in Windows 8.1 x64.

The obligue version is overriding the regular one. When I deleted oblique via Windows Font Manager, Monoid Regular suddenly appeared.

**Comment by larsenwork** [comment]
Hmm...not #22 but maybe #23 but I think it's actually something else. Pushing now so please try in ~15min when the release branch is updated.

**Comment by larsenwork** [comment]
@ElectronicWar hmm...then it's not what I suspected. Will have to check something else then.

**Comment by larsenwork** [comment]
It's currently cooking in circleci so ~12 min

**Comment by larsenwork** [comment]
@axd1967 @ElectronicWar the updated version is now live for you to try :)

**Comment by axd1967** [comment]
thx! tryig v0.52 
(tip: append the info you get from `git describe` to the version info, so you can see )

* bold and regular are now visible in the Font panel, but not oblique (nor retina)
* I can now use (I assume) regular in Android Studio.
* oblique is not visible, but Studio seems to be able to generate italic text, so I guess that's ok; but in Notepad++, italic does not seem possible, so that's not ok.

**Comment by larsenwork** [comment]
> (tip: append the info you get from git describe to the version info, so you can see from what git version the fonts were generated.)

Great tip - this is something for my man @chase 

Try removing the oblique and retina and install these two instead: 
https://dl.dropboxusercontent.com/u/3019777/Monoid-Italic.ttf
https://dl.dropboxusercontent.com/u/3019777/Monoid-Retina.ttf

**Comment by axd1967** [comment]
* meanwhile Notepad++ *does* see Oblique (but Font panel didn't).
* I installed your Monoid Italic and that now also appears in the Font panel
* Monoid Retina still not visible, but I assume this is more for Apple users

**Comment by larsenwork** [comment]
Oblique: Confused as to how Notepad can see oblique if you've removed it?
Italic: Great - bothers me since it's not an italic but an oblique but if that's what it takes to make it work in windows #75 
Retina: Should probably be called HDPI instead - it's for all users with high resolution displays regardless of operating system. What happens if you remove regular?

**Comment by ElectronicWar** [comment]
> Try removing the oblique and retina and install these two instead: 

They have the same issue from my test, the Retina one hides the Italic version. Whatever version I install first (Regular or Oblique) is the "dominant" font which is shown in the manager and gets loaded when I type "Monoid" in Sublime Text. Upon deleting the font, it's removed and the 2nd installed font will take its place. Monoid Bold does not have this issue. If I want a specific version I have to specify "Monoid Regular" as font name to get it for example, at least in Sublime.

The default Windows font selection dialog does find all styles:
![2015-07-27_13-56-25](https://cloud.githubusercontent.com/assets/1890874/8905537/6375e0be-3467-11e5-8de3-9fbf51434863.png)

Windows font list "hides" the 2nd installed as usual:
![2015-07-27_13-58-16](https://cloud.githubusercontent.com/assets/1890874/8905562/92e36574-3467-11e5-93b5-1ea84f6a79af.png)

Atom works properly, no matter if Regular or Oblique is the "dominant" font.

Sublime selects the dominant font when just entering "Monoid", but I can select the Regular by using "Monoid Regular" as font name if Oblique is dominant.
![2015-07-27_14-10-54](https://cloud.githubusercontent.com/assets/1890874/8905799/8bfb2c54-3469-11e5-8581-b41e4d0de5b0.png)

Notepad++ 6.8 behaves like Sublime in selecting the dominant font, but I cannot force it to use regular.
![2015-07-27_14-10-03](https://cloud.githubusercontent.com/assets/1890874/8905759/33f89dde-3469-11e5-8228-57ba3dc48738.png)

**Comment by larsenwork** [comment]
@axd1967 thanks - do you have an example of a open source monospaced font with regular, bold and italic that works in all editors?

**Comment by larsenwork** [comment]
@axd1967 and what happens if you only have retina, bold and italic installed?

**Comment by ElectronicWar** [comment]
@larsenwork Source Code Pro comes to mind. https://github.com/adobe-fonts/source-code-pro

**Comment by axd1967** [comment]
After installing Monoid-italic and -Retina,I got this:

![mono](https://cloud.githubusercontent.com/assets/3529789/8906505/80d97aaa-346f-11e5-976e-2b71f5a3d5f9.jpg)

`Monoid` opens into 

![m2](https://cloud.githubusercontent.com/assets/3529789/8906535/bd9d476e-346f-11e5-851f-37c9b44bccbe.jpg)

when I delete Regular, Oblique appears; NPP no longer shows a regular Monoid font.

![mreg](https://cloud.githubusercontent.com/assets/3529789/8906672/ad38820c-3470-11e5-9376-1f765c40e279.jpg)

this is messy, I now get a message that I cannot delete Oblique, while the 2 apps that were configured to use it have been reverted to different fonts. Probably need to reboot, I'm stopping this kind of testing, sorry.

**Comment by ElectronicWar** [comment]
@axd1967 You need to close the apps to delete the fonts, most will hold a lock until restarted even when a new font has been selected.

**Comment by larsenwork** [comment]
@axd1967 what @ElectronicWar most operating system caches the fonts so you have to at least close+reopen the programs in question and maybe also clear the system cache (mac has a terminal command for this - don't know about windows) by terminal command or reboot

**Comment by larsenwork** [comment]
@ElectronicWar what was the conclusion to all of this? (slightly confused) :smile:

**Comment by ElectronicWar** [comment]
@larsenwork Sorry if it's confusing. 0.52 has the same problem for me, as in Regular and Oblique hiding each other, depending on what is installed first, they are not recognized as different font styles by most applications and the one installed first is selected. You might want to look at how [Source Code Pro](https://github.com/adobe-fonts/source-code-pro) by Adobe is solving this.

**Comment by larsenwork** [comment]
@ElectronicWar Thanks, I've made a few changes to meta data in these: 
https://dl.dropboxusercontent.com/u/3019777/0.55/Monoid-Regular.ttf
https://dl.dropboxusercontent.com/u/3019777/0.55/Monoid-Italic.ttf
if you can try them? 

Delete old fonts
Quit programs + delete C:\Windows\System32\FNTCACHE.DAT 
Install new fonts

**Comment by ElectronicWar** [comment]
@larsenwork Those are working fine! I get the regular version when using "Monoid" and switching to italic style correctly loads the italic font instead of just tilting the regular style.
![2015-07-28_14-19-37](https://cloud.githubusercontent.com/assets/1890874/8931061/cdc9dc1e-3533-11e5-88ae-1f3168987d73.png)

![2015-07-28_14-21-16](https://cloud.githubusercontent.com/assets/1890874/8931070/f34664f8-3533-11e5-8773-8f17cc7a4666.png)

**Comment by larsenwork** [comment]
@ElectronicWar Cheers, thanks for testing :)

**Comment by larsenwork** [comment]
Will be updated in 0.55 soon so closing for now
