### ISSUE TITLE
= shows up as ≤ ligatures problem

### ISSUE THREAD

**Issue by ajpaulson** [larsenwork/monoid#73]
I downloaded the latest version about 20 minutes ago and tested on Ubuntu with an English US keymap set.

The equals sign shows up as a less than or equal sign with very close spacing so that it overlaps preceding characters.

**Comment by plgruener** [comment]
same as https://github.com/larsenwork/monoid/issues/31#issuecomment-125142718

**Comment by ajpaulson** [comment]
Ah I didn't realise this was a duplicate - I will close this and comment there.

**Closed as duplicate of #31**
