### ISSUE TITLE
Changing the name of Oblique to Italic

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#75]
@chase Do I need to change anything in the build scripts for this to work? 

(Unrelated but since we're talking about the script): How does this work https://github.com/larsenwork/monoid/blob/master/Scripts/fontbuilder.py#L199 - the fonts doesn't currently have a UniqueID?

**Comment by larsenwork** [comment]
Love the dragon btw...

**Comment by chase** [comment]
@larsenwork All you should have to do is change Oblique to Italic in `circle.yml`:
https://github.com/larsenwork/monoid/blob/master/circle.yml#L35

Regarding the UniqueID SFNT table entry, that's something that is generated by FontForge automatically. Don't worry about it.

**Comment by larsenwork** [comment]
Cheers, why is it retina isn't on that list?

**Comment by chase** [comment]
That's only for fonts used on GitHub pages.

**Comment by larsenwork** [comment]
:+1: changing it for next update

**Comment by larsenwork** [comment]
done
