### ISSUE TITLE
Support for Notepad++?

### ISSUE THREAD

**Issue by GaurangTandon** [larsenwork/monoid#77]
I have already downloaded that zip file. But, how do I enable this font for Notepad++ on Windows 7? I looked in the Settings but there isn't anything much. The only font related menu provides me a pre-defined list of fonts, and no option to load a new one (like Monoid).

Please help! I really want to use Monoid :-)

**Comment by plgruener** [comment]
You first have to install the font to the whole System (Win7), before you can use it.
To do so, see [microsoft website](https://www.microsoft.com/en-us/Typography/TrueTypeInstall.aspx)
So try unzip, double-click on Monoid-*.ttf, select install. (I did not test this though).

**Comment by larsenwork** [comment]
Hmm...as monoid seems to be reaching a broader audience we might need to add simple installation guides for people not familiar with installing fonts

**Comment by larsenwork** [comment]
Assumed solved. I also added win instructions to the readme.

**Comment by GaurangTandon** [comment]
@plgruener @larsenwork Thanks for your help!
