### ISSUE TITLE
Create a larsenwork/homebrew-monoid tap

### ISSUE THREAD

**Issue by sscotth** [larsenwork/monoid#80]
It can easily be updated with the release script, and preferably owned under your larsenwork github. 

Example casks:

```rb
cask :v1 => 'font-monoid' do
  version :latest
  sha256 :no_check

  # github.com is the official download host per the vendor homepage
  url 'https://github.com/larsenwork/monoid/blob/release/Monoid.zip?raw=true'
  homepage 'http://larsenwork.com/monoid/'
  license :ofl

  font 'Monoid-Bold.ttf'
  font 'Monoid-Oblique.ttf'
  font 'Monoid-Regular.ttf'
  font 'Monoid-Retina.ttf'
end
```

```rb
cask :v1 => 'font-monoid-xtralarge-dollar-asterisk-l-nocalt' do
  version :latest
  sha256 :no_check

  # github.com is the official download host per the vendor homepage
  url 'https://github.com/larsenwork/monoid/blob/release/Monoid-XtraLarge-Dollar-Asterisk-l-NoCalt.zip?raw=true'
  homepage 'http://larsenwork.com/monoid/'
  license :ofl

  font 'Monoid-Bold-XtraLarge-Dollar-Asterisk-l-NoCalt.ttf'
  font 'Monoid-Oblique-XtraLarge-Dollar-Asterisk-l-NoCalt.ttf'
  font 'Monoid-Regular-XtraLarge-Dollar-Asterisk-l-NoCalt.ttf'
  font 'Monoid-Retina-XtraLarge-Dollar-Asterisk-l-NoCalt.ttf'
end
```

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md
https://github.com/caskroom/homebrew-fonts/pull/364

**Comment by larsenwork** [comment]
Using https://github.com/larsenwork/monoid/blob/release/Monoid.zip?raw=true links is a no-go as far as I've understood? 
We're currently using rawgit + version.js to serve the binaries.

A quick glance in the other thread lead me to believe it has already been added?

**Comment by sscotth** [comment]
They are probably going to add the base font, but all the variants will need their own cask

Homebrew, from what I understand, doesn't really have a consensus on this, but several casks use "raw=true", and I can't find any that use rawgit. Either way, I don't think that is a big deal and can use rawgit.

https://github.com/caskroom/homebrew-cask/search?p=2&q=github+raw&type=Code&utf8=%E2%9C%93

https://github.com/caskroom/homebrew-fonts/search?utf8=%E2%9C%93&q=github+raw

**Comment by sscotth** [comment]
Also, you can reference the latest version with `https://cdn.rawgit.com/larsenwork/monoid/release/Monoid.zip` like I did above, or you can use the versioned like this:

```rb
cask :v1 => 'font-monoid' do
  version '0.53'
  sha256 '8413e4308ef10b7121982d81f1c68d29e27ebcceccb536b00458cdb3f275b00d'

  # rawgit.com is the official download host per the vendor homepage
  url 'https://cdn.rawgit.com/larsenwork/monoid/4d2022f8083116435127c863977281ac658de735/Monoid.zip'
  homepage 'http://larsenwork.com/monoid/'
  license :ofl

  font 'Monoid-Bold.ttf'
  font 'Monoid-Oblique.ttf'
  font 'Monoid-Regular.ttf'
  font 'Monoid-Retina.ttf'

  caveats <<-EOS.undent
  #{token} only installs the Normal weight with medium line height.
  To get other styles, please tap the larsenwork/homebrew-monoid repo
    brew tap larsenwork/homebrew-monoid
  EOS
end
```

and 

```rb
cask :v1 => 'font-monoid-xtralarge-dollar-asterisk-l-nocalt' do
  version '0.53'
  sha256 '5e1e2472079236a2ad07b844545bc56a5e83c8989424957821313b8b36318d7e'

  # rawgit.com is the official download host per the vendor homepage
  url 'https://cdn.rawgit.com/larsenwork/monoid/4d2022f8083116435127c863977281ac658de735/Monoid-XtraLarge-Dollar-Asterisk-l-NoCalt.zip'
  homepage 'http://larsenwork.com/monoid/'
  license :ofl

  font 'Monoid-Bold-XtraLarge-Dollar-Asterisk-l-NoCalt.ttf'
  font 'Monoid-Oblique-XtraLarge-Dollar-Asterisk-l-NoCalt.ttf'
  font 'Monoid-Regular-XtraLarge-Dollar-Asterisk-l-NoCalt.ttf'
  font 'Monoid-Retina-XtraLarge-Dollar-Asterisk-l-NoCalt.ttf'
end
```

**Comment by larsenwork** [comment]
Ok, thanks for the clarification - problem with all the versions is they might change over time based on user input (e.g. I'm soon changing the default 3 so what used to the alternate will be the default and vice versa) so for now I think it's better just telling people to stop by larsenwork.com/monoid

**Comment by sscotth** [comment]
I believe this will stabilize quickly, but I think no matter what solution, there will be people that might get caught by a default switch like you mentioned.

**Comment by larsenwork** [comment]
Seems like work with little or no gain to me to be honest. I'm perfectly fine with just the default version being added to default Caskroom-fonts and pointing users to larsenwork.com/monoid for custom versions.
But thanks for the suggestion and clarifications :+1:
