### ISSUE TITLE
10 pt missing horizontal bar on A and 4 (windows)

### ISSUE THREAD

**Issue by chuckfossen** [larsenwork/monoid#81]
Using the 10 pt font on windows, the horizontal bar on A and 4 is missing.
![10pt](https://cloud.githubusercontent.com/assets/13524728/8911669/91b26c0e-3453-11e5-9269-d022449f72c4.png)

**Comment by larsenwork** [comment]
Yep, as expected. You are using it at a smaller size than it was designed for and by the looks of it you don't have antialiasing turned on.

**Comment by KarolS** [comment]
Similar issue at sizes 12 and 14, without antialiasing.

13, 15 and 16 look fine.

Enabling antialiasing makes it render the bar correctly, but the text simply gets blurry at any size.

**Comment by larsenwork** [comment]
@KarolS is http://larsenwork.com/monoid also blurry?

**Comment by larsenwork** [comment]
I think 11.25pt is the correct font size for Windows although I'm not sure

**Comment by KarolS** [comment]
Sorry, my mistake, 15 is not blurry.

13, 17 and 19 are only blurred horizontally. It looks fine though.

Even sizes are blurred in all directions. At 12 and 14 it looks bad, 

I think people who are fine with odd sizes should be fine, only those who want smaller even sizes may complain.

**Comment by larsenwork** [comment]
@KarolS could you try this at 12pt: https://dl.dropboxusercontent.com/u/3019777/Monoid-Regular.ttf

**Comment by larsenwork** [comment]
@chuckfossen forgot to mention you: could you also try this at 12pt: https://dl.dropboxusercontent.com/u/3019777/Monoid-Regular.ttf

**Comment by chuckfossen** [comment]
@larsenwork, https://dl.dropboxusercontent.com/u/3019777/Monoid-Regular.ttf looks much better at 10 pt. Thanks!

**Comment by larsenwork** [comment]
@chuckfossen cheers, screenshot?

**Comment by chuckfossen** [comment]
![monoid 10pt](https://cloud.githubusercontent.com/assets/13524728/8934781/f0ac673a-350e-11e5-9f53-ac2f317ba714.png)

**Comment by larsenwork** [comment]
:+1: could you quickly take a screenshot of 12pt too?

**Comment by chuckfossen** [comment]
Here's 12pt:
![monoid 12pt](https://cloud.githubusercontent.com/assets/13524728/8935597/38f472b8-3513-11e5-863b-441c8b3a823c.png)

**Comment by chuckfossen** [comment]
For reference, I compare new fonts against my "gold standard" bitmap font:
![fixed font](https://cloud.githubusercontent.com/assets/13524728/8935709/b4646796-3513-11e5-9c36-9bc1a6a749d4.png)
There are some applications that can't handle bitmapped fonts anymore. :(

**Comment by larsenwork** [comment]
@chuckfossen check out #53 if bitmaps are you thing

**Comment by chuckfossen** [comment]
For completeness, I just realized the 10pt equal sign looks like a minus sign.

**Comment by larsenwork** [comment]
yep, for website version 11.25 pt is the sweet spot - the dropbox one is 12 pt

**Comment by larsenwork** [comment]
@chuckfossen could you try this at 9pt? https://dl.dropboxusercontent.com/u/3019777/9pt/Monoid-Regular.ttf
