### ISSUE TITLE
ligatures not working in Notepad++

### ISSUE THREAD

**Issue by barttt** [larsenwork/monoid#83]
Nice font, thanks for the hard work..
I just installed, noting the issues found by others having to do with the order of installing..
I download with ligatures turned on, but Notepad++ does not display them. I had hoped for the != and >= ligatures to display properly.
Hopefully this is an easy fix

**Comment by larsenwork** [comment]
I'm not sure how much I can do about it as it's probably because notepad++ doesn't support opentype features in fonts - I'm using "calt" and "liga". @donho would know.

**Comment by barttt** [comment]
perhaps its time for me to update to a new editor them..
Thanks for the quick reply

**Comment by larsenwork** [comment]
@barttt no problem - although it sounds a bit drastic unless you've thought about that for a while :)
