### ISSUE TITLE
Updating the J

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#84]
Any thoughts on this vs current:

![screen shot 2015-07-28 at 00 01 32](https://cloud.githubusercontent.com/assets/3859425/8918948/dcdfb156-34bb-11e5-84a6-4d7995cb4669.png)

**Comment by larsenwork** [comment]
Made some minor adjustments to it but I really like so I'll add it

**Comment by plgruener** [comment]
I do like it, too :+1: 
thought about making the upper bar (however that's called) a little shorter, but I assume that's difficult due to the grid?

**Comment by larsenwork** [comment]
@plgruener yep, retina bar will be ½ px shorter though
