### ISSUE TITLE
Characters not horizontally centered

### ISSUE THREAD

**Issue by plgruener** [larsenwork/monoid#86]
Most Characters seem to be not centered (horizontally), but shifted to the right.
This is odd when it comes to highlighting text. Or is this intended?
![monoid-a](https://cloud.githubusercontent.com/assets/5796100/8919281/5af79b7e-34be-11e5-9961-3eeb11f2aac7.png)
![monoid-e](https://cloud.githubusercontent.com/assets/5796100/8919288/6057e948-34be-11e5-84f6-34ca47c19b7f.png)

**Comment by larsenwork** [comment]
Intended. It's because of the grid fit. Looks odd but it's the only way I could get pixel crispness at 15px with the spacing I wanted.
