### ISSUE TITLE
Only run circleci when changes are made to the master branch

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#88]
@chase obviously :smile: 
Is this possible? I just created the 0.55 branch to work on some features and leave the master branch for bugfixes and minor upgrades. 

Running with error
![screen shot 2015-07-28 at 12 30 45](https://cloud.githubusercontent.com/assets/3859425/8929285/8c5b1892-3524-11e5-80da-0c6c3e340fd0.png)

But continues instead of stopping
![screen shot 2015-07-28 at 12 30 53](https://cloud.githubusercontent.com/assets/3859425/8929284/8c36c9ec-3524-11e5-9983-a1631dd671c7.png)

I pushed an update to master immediately after so I didn't get to check the release branch after the 0.55 build ran.

**Comment by chase** [comment]
White-listing caused issues before, but I'll get this fixed in a second.

**Comment by chase** [comment]
By the way, you can always cancel a build if it delays something.

**Comment by larsenwork** [comment]
:+1:

**Comment by larsenwork** [comment]
![screen shot 2015-07-28 at 17 47 31](https://cloud.githubusercontent.com/assets/3859425/8936121/c9d5c312-3550-11e5-8e26-749d0ac07d62.png)

I'm afraid it doesn't work.

**Comment by chase** [comment]
The image you posted has nothing to do with CircleCI, either. That is merely Github saying you've made changes.

You haven't merged the changes in `master` into `0.55`. Once you merge master into `0.55` it will update the `circle.yml` file that CircleCI relies upon.

Per-CircleCI's documentation:

> We discourage branch whitelisting, it means work-in-progress code can go a long time without being integrated and tested and we've found it leads to problems when that untested code gets merged.
>
> circle.yml is per-branch configuration file, and the branch ignore list in one branch will only affect that branch and no other one.

**Comment by larsenwork** [comment]
The picture shows that a changes pushed to the 0.55 branch ends up in the release branch which they absolutely shouldn't. 

Not too big of an issue as I can press "cancel" in circleci everytime I push to a branch other than master.

**Comment by larsenwork** [comment]
Qu'est-ce que c'est? :)

![screen shot 2015-07-28 at 18 23 50](https://cloud.githubusercontent.com/assets/3859425/8936999/f67b751a-3555-11e5-927d-0eea823fb4fa.png)

**Comment by chase** [comment]
You also don't have to push a change to master, just run a rebuild in the CircleCI.

That's me fixing your branch so it doesn't build on CircleCI, as I explained above. I merged in master, preferring `0.55` changes.

**Comment by chase** [comment]
Again, this is solved, but you need to make sure you have `master` merged into your local branches or else it *won't work*. Each branch's local `circle.yml` file determines what is built. I know, that makes no sense, but that's how it is.

**Comment by chase** [comment]
After this is settled, please be aware that I won't be able to work on the project for a couple of weeks.

**Comment by larsenwork** [comment]
Cheers. I'm also doing a push the next couple of days and then prolly quite quiet until september. 

Having master merged into a branch is not really how branches normally work is it? I normally do it the other way around: work in a branch and when done: pull it into master. 

I think I'd rather just push and then press cancel every time than having a backwards workflow.

ps. The latest release was made pressing "rebuild" - nifty feature.

**Comment by larsenwork** [comment]
Ah...now I think I understand. It's because circle.yml in 0.55 didn't have the whitelist update?

**Comment by chase** [comment]
Yes.

Also, that's not a backwards workflow, branches have no direction. When you merge into master, there will be no conflicts.

It actually is *very* common to rebase a feature branch onto master; however, since we both have access to `0.55` it is bad to rebase since that rewrites commit history. You should *never* rewrite remote branch histories, but merging is okay.

**Comment by larsenwork** [comment]
Got it! Thanks

**Comment by larsenwork** [comment]
:clap: 
![screen shot 2015-07-28 at 18 40 08](https://cloud.githubusercontent.com/assets/3859425/8937350/1e10bd18-3558-11e5-9b6e-b623efbdff31.png)

**Comment by chase** [comment]
![Taking a bow] (http://31.media.tumblr.com/740f90580de520b93afdcb2bae632857/tumblr_inline_mtcf2wUtbw1rwwk99.gif)
