### ISSUE TITLE
Proper releasing

### ISSUE THREAD

**Issue by elmariofredo** [larsenwork/monoid#89]
Thank you for awesome font, but please can you start doing proper versioned releases like e.g. https://github.com/belluzj/fantasque-sans/releases so we can track changes and much more easily distribute new versions.

I had to guess your current version 0.1.3 by looking in https://github.com/larsenwork/monoid/tree/release and created pull request to caskroom fonts caskroom/homebrew-fonts#367 with proper versioning it would have been much easier.

Cheers!

**Comment by elmariofredo** [comment]
please ignore this didn't realize that you have gazilion variants of your font. it's already discussed in caskroom/homebrew-fonts#364

**Comment by larsenwork** [comment]
:+1: "only" 3200 :wink:

**Comment by elmariofredo** [comment]
:smile:
