### ISSUE TITLE
Any thoughts on the new readme header?

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#91]
You can see it here: https://github.com/larsenwork/monoid/tree/0.55#readme

I didn't like the table and wanted a cleaner look + badges (I know it's a fad)

**Comment by plgruener** [comment]
Looks ok to me. If you're at it:
* add version info to downloadsite
* maybe add a category "how to build from source" / "how to contribute"

**Comment by larsenwork** [comment]
Added version to the website.
How to build from source would be a long chapter quickly. 
I only think "How to contribute" is relevant if you're doing something other than the default github model.

**Comment by larsenwork** [comment]
merged 0.55 into master
