### ISSUE TITLE
Testing: Switch to 12px and 9pt as default sizes

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#95]
1. Quit your program
2. Download and install https://dl.dropboxusercontent.com/u/3019777/9pt/Monoid-Regular.ttf
3. Reopen your program and set font size to
  - 12px on Mac
  - 9pt on Windows

Tell me if it looks good or if there are any issues. 

Thanks:)

**Comment by larsenwork** [comment]
@tharibo, @chuckfossen, @KarolS :smile:

**Comment by plgruener** [comment]
Linux (gedit), 9pt. looks ok to me (and 9pt is my preferable coding size, so thanks).
except for the <= >= ligatures, which are still pretty blurry (but were so before).
![monoid-9pt](https://cloud.githubusercontent.com/assets/5796100/8954601/030cae3e-35e7-11e5-93c1-e004f754957c.png)

**Comment by larsenwork** [comment]
Cheers - it's just a number though, same size as previous 15px/11.25pt :wink: 
Not sure if much can be done about the >= ligature...difficult to grid fit slanted lines

**Comment by tharibo** [comment]
Hey Andreas.

Here's the result:
![image](https://cloud.githubusercontent.com/assets/5548348/8957293/c161a892-35fd-11e5-8833-73cd4ad0b975.png)

Ligatures don't work better with this version, but it's possible that rendering is sharper... in a good sense.

**Comment by larsenwork** [comment]
@tharibo thanks - yeah I'm not sure anything can be done to fix those from my point of view. I don't know if there's a forum for your editor where you can report the bug?

**Comment by tharibo** [comment]
Well I can try to find one. Microsoft is releasing a lot of software in open source, but AFAIK, not Visual Studio... yet.

How can I describe the bug there? I'm in no way familiar with how the ligatures work or even how a font is built.

**Comment by larsenwork** [comment]
@tharibo for e.g. -> I'm using the opentype feature called "calt" 

It's the same feature I'm using for e.g. >= which seems to work so I'm thinking they must do something with the "hyphen-minus" sign. 

http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#5.f
http://graphemica.com/-

**Comment by ElectronicWar** [comment]
Looks great on Sublime 3 (Windows 8.1 x64).
It's in a really good size now for me to consider as new main font, the old 14pt was just too big on my 1680x1050 displays.

![2015-07-29_16-28-59](https://cloud.githubusercontent.com/assets/1890874/8960176/08f92278-360f-11e5-81df-03ad6ffb7d6d.png)

**Comment by larsenwork** [comment]
@ElectronicWar thanks, low res displays at 12px/9pt is where Monoid really shines compared to most other coding fonts :smile:

**Comment by larsenwork** [comment]
So it looks fine on Win, Linux and Mac :smirk:
